// SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, dir, name, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
		t.Fatalf("writing %s: %v", name, err)
	}
}

func TestCollectViolationsFindsUndocumentedFunctions(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "documented.go", "package x\n\n// Foo greets.\nfunc Foo() {}\n\n// bar helps.\nfunc bar() {}\n")
	write(t, root, "undocumented.go", "package x\n\nfunc Bare() {}\n\ntype T struct{}\n\nfunc (T) Method() {}\n")
	write(t, root, "generated.go", "// Code generated by hand. DO NOT EDIT.\n\npackage x\n\nfunc Gen() {}\n")
	write(t, root, "helpers_test.go", "package x\n\nfunc Helper() {}\n")

	violations, err := collectViolations(root)

	if err != nil {
		t.Fatalf("collectViolations() error = %v, want nil", err)
	}
	names := make([]string, 0, len(violations))
	for _, v := range violations {
		names = append(names, v.name)
	}
	want := map[string]bool{"Bare": true, "Method": true}
	if len(names) != len(want) {
		t.Fatalf("violations = %v, want exactly the undocumented production funcs %v", names, want)
	}
	for _, name := range names {
		if !want[name] {
			t.Errorf("unexpected violation %q, want only %v", name, want)
		}
	}
}

func TestRunReportsAndFailsOnViolations(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "bad.go", "package x\n\nfunc Undocumented() {}\n")

	if err := run(root, os.Stderr); err == nil {
		t.Fatal("run() error = nil, want a failure listing the violation")
	}
}

func TestRunPassesWhenEveryFunctionIsDocumented(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "good.go", "package x\n\n// Ok is documented.\nfunc Ok() {}\n")

	if err := run(root, os.Stderr); err != nil {
		t.Fatalf("run() error = %v, want nil", err)
	}
}

func TestCollectViolationsReportsAMissingRoot(t *testing.T) {
	t.Parallel()

	if _, err := collectViolations(filepath.Join(t.TempDir(), "absent")); err == nil {
		t.Fatal("collectViolations() error = nil, want a walk error for a missing root")
	}
}

func TestCollectViolationsSkipsIgnoredDirectories(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	vendored := filepath.Join(root, "node_modules")
	if err := os.MkdirAll(vendored, 0o755); err != nil {
		t.Fatalf("creating node_modules: %v", err)
	}
	write(t, vendored, "vendored.go", "package x\n\nfunc Bare() {}\n")

	violations, err := collectViolations(root)

	if err != nil {
		t.Fatalf("collectViolations() error = %v, want nil", err)
	}
	if len(violations) != 0 {
		t.Errorf("violations = %v, want none from an ignored directory", violations)
	}
}

func TestCollectViolationsReportsUnparseableFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	write(t, root, "broken.go", "package x\n\nfunc (")

	if _, err := collectViolations(root); err == nil {
		t.Fatal("collectViolations() error = nil, want a parse error")
	}
}

func TestRunReportsCollectionFailure(t *testing.T) {
	t.Parallel()

	if err := run(filepath.Join(t.TempDir(), "absent"), os.Stderr); err == nil {
		t.Fatal("run() error = nil, want the walk error propagated")
	}
}

func TestRepositoryIsFullyDocumented(t *testing.T) {
	t.Parallel()

	violations, err := collectViolations(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("collectViolations() error = %v, want nil", err)
	}
	for _, v := range violations {
		t.Errorf("%s:%d: %s is missing a doc comment", v.file, v.line, v.name)
	}
}
