// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/gopherium/gophenberg/internal/content"
)

const addRelation = `-- name: AddRelation :exec
INSERT INTO core.content_relations (from_id, field_id, to_id, position, sort_at, visible)
SELECT $1, $2, $3, $4, coalesce(c.published_at, c.created_at),
    c.status = 'published'
FROM core.content c
WHERE c.id = $1
`

type AddRelationParams struct {
	FromID   uuid.UUID
	FieldID  int32
	ToID     uuid.UUID
	Position int32
}

func (q *Queries) AddRelation(ctx context.Context, arg AddRelationParams) error {
	_, err := q.db.Exec(ctx, addRelation,
		arg.FromID,
		arg.FieldID,
		arg.ToID,
		arg.Position,
	)
	return err
}

const clearRelationsOfField = `-- name: ClearRelationsOfField :exec
DELETE FROM core.content_relations WHERE from_id = $1 AND field_id = $2
`

type ClearRelationsOfFieldParams struct {
	FromID  uuid.UUID
	FieldID int32
}

func (q *Queries) ClearRelationsOfField(ctx context.Context, arg ClearRelationsOfFieldParams) error {
	_, err := q.db.Exec(ctx, clearRelationsOfField, arg.FromID, arg.FieldID)
	return err
}

const contentDepth = `-- name: ContentDepth :one
WITH RECURSIVE below AS (
    SELECT c.id, 0 AS level
    FROM core.content c
    WHERE c.id = $1
    UNION ALL
    SELECT child.id, below.level + 1
    FROM core.content child
    JOIN below ON child.parent_id = below.id
)
SELECT coalesce(max(level), 0)::int FROM below
`

func (q *Queries) ContentDepth(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, contentDepth, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM core.content p WHERE p.parent_id = $1
`

func (q *Queries) CountChildren(ctx context.Context, id *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContent = `-- name: CountContent :one
SELECT count(*)
FROM core.content p
WHERE p.type = $1
    AND ($2::jsonb = '{}'::jsonb OR p.fields @> $2::jsonb)
    AND (cardinality($3::text[]) = 0 OR p.status = ANY($3::text[]))
    AND (cardinality($4::uuid[]) = 0 OR p.author_id = ANY($4::uuid[]))
    AND p.author_id <> ALL($5::uuid[])
    AND ($6::timestamptz IS NULL
        OR COALESCE(p.published_at, p.updated_at) < $6::timestamptz)
    AND ($7::timestamptz IS NULL
        OR COALESCE(p.published_at, p.updated_at) > $7::timestamptz)
    AND (
        $8::text = ''
        OR p.title ILIKE '%' || $8 || '%'
        OR p.content ILIKE '%' || $8 || '%'
    )
`

type CountContentParams struct {
	Type            string
	FieldFilter     []byte
	Statuses        []string
	Authors         []uuid.UUID
	ExcludedAuthors []uuid.UUID
	Before          *time.Time
	After           *time.Time
	Search          string
}

func (q *Queries) CountContent(ctx context.Context, arg CountContentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContent,
		arg.Type,
		arg.FieldFilter,
		arg.Statuses,
		arg.Authors,
		arg.ExcludedAuthors,
		arg.Before,
		arg.After,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContentByStatus = `-- name: CountContentByStatus :many
SELECT p.status, count(*) AS total
FROM core.content p
WHERE p.type = $1
GROUP BY p.status
`

type CountContentByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountContentByStatus(ctx context.Context, type_ string) ([]CountContentByStatusRow, error) {
	rows, err := q.db.Query(ctx, countContentByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountContentByStatusRow
	for rows.Next() {
		var i CountContentByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPointingAt = `-- name: CountPointingAt :one
SELECT count(DISTINCT r.from_id)
FROM core.content_relations r
JOIN core.content c ON c.id = r.from_id
JOIN core.content_types t ON t.key = c.type
WHERE r.to_id = $1 AND r.field_id = $2 AND r.visible AND t.active
`

type CountPointingAtParams struct {
	Target uuid.UUID
	Field  int32
}

func (q *Queries) CountPointingAt(ctx context.Context, arg CountPointingAtParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPointingAt, arg.Target, arg.Field)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelatedContent = `-- name: CountRelatedContent :one
SELECT count(DISTINCT r.from_id)
FROM core.content_relations r
JOIN core.content c ON c.id = r.from_id
JOIN core.content_types t ON t.key = c.type
WHERE r.to_id = $1 AND r.visible AND t.active
`

func (q *Queries) CountRelatedContent(ctx context.Context, target uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelatedContent, target)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrash = `-- name: CountTrash :one
SELECT count(*) FROM core.content p WHERE p.type = $1 AND p.status = 'trash'
`

func (q *Queries) CountTrash(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countTrash, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContent = `-- name: CreateContent :one

INSERT INTO core.content (
    id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at, parent_id, path, fields
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at, parent_id, path, fields
`

type CreateContentParams struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.AuthorID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ParentID,
		arg.Path,
		arg.Fields,
	)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO core.content_revisions (
    id, content_id, kind, author_id, title, content, excerpt, fields, created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateRevisionParams struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.Exec(ctx, createRevision,
		arg.ID,
		arg.ContentID,
		arg.Kind,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.CreatedAt,
	)
	return err
}

const deleteAutosave = `-- name: DeleteAutosave :exec
DELETE FROM core.content_revisions AS r
WHERE r.content_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type DeleteAutosaveParams struct {
	ContentID uuid.UUID
	AuthorID  uuid.UUID
}

func (q *Queries) DeleteAutosave(ctx context.Context, arg DeleteAutosaveParams) error {
	_, err := q.db.Exec(ctx, deleteAutosave, arg.ContentID, arg.AuthorID)
	return err
}

const deleteAutosavesOfContent = `-- name: DeleteAutosavesOfContent :exec
DELETE FROM core.content_revisions AS r
WHERE r.content_id = $1 AND r.kind = 'autosave'
`

func (q *Queries) DeleteAutosavesOfContent(ctx context.Context, contentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAutosavesOfContent, contentID)
	return err
}

const deleteContent = `-- name: DeleteContent :execrows
DELETE FROM core.content AS p WHERE p.id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevision = `-- name: DeleteRevision :execrows
DELETE FROM core.content_revisions AS r
WHERE r.content_id = $1 AND r.id = $2
`

type DeleteRevisionParams struct {
	ContentID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteRevision(ctx context.Context, arg DeleteRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevision, arg.ContentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrash = `-- name: DeleteTrash :execrows
DELETE FROM core.content AS p
WHERE p.type = $1 AND p.status = 'trash'
    AND ($2::uuid IS NULL OR p.author_id = $2::uuid)
`

type DeleteTrashParams struct {
	Type     string
	AuthorID *uuid.UUID
}

func (q *Queries) DeleteTrash(ctx context.Context, arg DeleteTrashParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrash, arg.Type, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAutosave = `-- name: GetAutosave :one
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.fields, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type GetAutosaveParams struct {
	ContentID uuid.UUID
	AuthorID  uuid.UUID
}

type GetAutosaveRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) GetAutosave(ctx context.Context, arg GetAutosaveParams) (GetAutosaveRow, error) {
	row := q.db.QueryRow(ctx, getAutosave, arg.ContentID, arg.AuthorID)
	var i GetAutosaveRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const getContent = `-- name: GetContent :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.id = $1
`

func (q *Queries) GetContent(ctx context.Context, id uuid.UUID) (CoreContent, error) {
	row := q.db.QueryRow(ctx, getContent, id)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const getPublishedContentByPath = `-- name: GetPublishedContentByPath :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.path = $1 AND p.status = 'published'
`

func (q *Queries) GetPublishedContentByPath(ctx context.Context, path string) (CoreContent, error) {
	row := q.db.QueryRow(ctx, getPublishedContentByPath, path)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.fields, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1 AND r.id = $2
`

type GetRevisionParams struct {
	ContentID uuid.UUID
	ID        uuid.UUID
}

type GetRevisionRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (GetRevisionRow, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.ContentID, arg.ID)
	var i GetRevisionRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const listContent = `-- name: ListContent :many
SELECT p.id, p.type, p.status, p.slug, p.title, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields,
    u.name AS author_name
FROM core.content p
JOIN auth.users u ON u.id = p.author_id
LEFT JOIN core.content parent ON parent.id = p.parent_id
WHERE p.type = $1
    AND ($2::jsonb = '{}'::jsonb OR p.fields @> $2::jsonb)
    AND (cardinality($3::text[]) = 0 OR p.status = ANY($3::text[]))
    AND (cardinality($4::uuid[]) = 0 OR p.author_id = ANY($4::uuid[]))
    AND p.author_id <> ALL($5::uuid[])
    AND ($6::timestamptz IS NULL
        OR COALESCE(p.published_at, p.updated_at) < $6::timestamptz)
    AND ($7::timestamptz IS NULL
        OR COALESCE(p.published_at, p.updated_at) > $7::timestamptz)
    AND (
        $8::text = ''
        OR p.title ILIKE '%' || $8 || '%'
        OR p.content ILIKE '%' || $8 || '%'
    )
ORDER BY
    CASE WHEN $9::text = 'title' AND $10::text = 'asc' THEN p.title END ASC,
    CASE WHEN $9::text = 'title' AND $10::text <> 'asc' THEN p.title END DESC,
    CASE WHEN $9::text = 'author' AND $10::text = 'asc' THEN u.name END ASC,
    CASE WHEN $9::text = 'author' AND $10::text <> 'asc' THEN u.name END DESC,
    CASE WHEN $9::text = 'slug' AND $10::text = 'asc' THEN p.slug END ASC,
    CASE WHEN $9::text = 'slug' AND $10::text <> 'asc' THEN p.slug END DESC,
    CASE WHEN $9::text = 'parent' AND $10::text = 'asc' THEN parent.created_at END ASC NULLS FIRST,
    CASE WHEN $9::text = 'parent' AND $10::text <> 'asc' THEN parent.created_at END DESC NULLS LAST,
    CASE WHEN $9::text NOT IN ('title', 'author', 'slug', 'parent') AND $10::text = 'asc'
        THEN COALESCE(p.published_at, p.updated_at) END ASC,
    CASE WHEN $9::text NOT IN ('title', 'author', 'slug', 'parent') AND $10::text <> 'asc'
        THEN COALESCE(p.published_at, p.updated_at) END DESC,
    p.id DESC
LIMIT $12 OFFSET $11
`

type ListContentParams struct {
	Type            string
	FieldFilter     []byte
	Statuses        []string
	Authors         []uuid.UUID
	ExcludedAuthors []uuid.UUID
	Before          *time.Time
	After           *time.Time
	Search          string
	OrderBy         string
	OrderDir        string
	RowOffset       int32
	RowLimit        int32
}

type ListContentRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
	AuthorName  string
}

func (q *Queries) ListContent(ctx context.Context, arg ListContentParams) ([]ListContentRow, error) {
	rows, err := q.db.Query(ctx, listContent,
		arg.Type,
		arg.FieldFilter,
		arg.Statuses,
		arg.Authors,
		arg.ExcludedAuthors,
		arg.Before,
		arg.After,
		arg.Search,
		arg.OrderBy,
		arg.OrderDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentRow
	for rows.Next() {
		var i ListContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Path,
			&i.Fields,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNestedContent = `-- name: ListNestedContent :many
WITH RECURSIVE listed AS (
    SELECT p.id, p.parent_id, row_number() OVER (ORDER BY
        CASE WHEN $3::text = 'title' AND $4::text = 'asc' THEN p.title END ASC,
        CASE WHEN $3::text = 'title' AND $4::text <> 'asc' THEN p.title END DESC,
        CASE WHEN $3::text = 'author' AND $4::text = 'asc' THEN u.name END ASC,
        CASE WHEN $3::text = 'author' AND $4::text <> 'asc' THEN u.name END DESC,
        CASE WHEN $3::text = 'slug' AND $4::text = 'asc' THEN p.slug END ASC,
        CASE WHEN $3::text = 'slug' AND $4::text <> 'asc' THEN p.slug END DESC,
        CASE WHEN $3::text = 'parent' AND $4::text = 'asc'
            THEN parent.created_at END ASC NULLS FIRST,
        CASE WHEN $3::text = 'parent' AND $4::text <> 'asc'
            THEN parent.created_at END DESC NULLS LAST,
        CASE WHEN $3::text NOT IN ('title', 'author', 'slug', 'parent') AND $4::text = 'asc'
            THEN COALESCE(p.published_at, p.updated_at) END ASC,
        CASE WHEN $3::text NOT IN ('title', 'author', 'slug', 'parent') AND $4::text <> 'asc'
            THEN COALESCE(p.published_at, p.updated_at) END DESC,
        p.id DESC
    ) AS place
    FROM core.content p
    JOIN auth.users u ON u.id = p.author_id
    LEFT JOIN core.content parent ON parent.id = p.parent_id
    WHERE p.type = $5
        AND ($6::jsonb = '{}'::jsonb OR p.fields @> $6::jsonb)
        AND (cardinality($7::text[]) = 0 OR p.status = ANY($7::text[]))
        AND (cardinality($8::uuid[]) = 0 OR p.author_id = ANY($8::uuid[]))
        AND p.author_id <> ALL($9::uuid[])
        AND ($10::timestamptz IS NULL
            OR COALESCE(p.published_at, p.updated_at) < $10::timestamptz)
        AND ($11::timestamptz IS NULL
            OR COALESCE(p.published_at, p.updated_at) > $11::timestamptz)
        AND (
            $12::text = ''
            OR p.title ILIKE '%' || $12 || '%'
            OR p.content ILIKE '%' || $12 || '%'
        )
), siblings AS (
    SELECT l.id, l.parent_id, l.place, min(l.place) OVER (PARTITION BY l.parent_id) AS first_place
    FROM listed l
), tree AS (
    SELECT s.id,
        CASE WHEN s.parent_id IS NULL THEN ARRAY[0, s.place] ELSE ARRAY[1, s.first_place, s.place] END AS trail
    FROM siblings s
    WHERE s.parent_id IS NULL OR NOT EXISTS (SELECT 1 FROM listed kept WHERE kept.id = s.parent_id)
  UNION ALL
    SELECT s.id, tree.trail || s.place
    FROM siblings s
    JOIN tree ON s.parent_id = tree.id
)
SELECT p.id, p.type, p.status, p.slug, p.title, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields,
    u.name AS author_name
FROM tree t
JOIN core.content p ON p.id = t.id
JOIN auth.users u ON u.id = p.author_id
ORDER BY t.trail
LIMIT $2 OFFSET $1
`

type ListNestedContentParams struct {
	RowOffset       int32
	RowLimit        int32
	OrderBy         string
	OrderDir        string
	Type            string
	FieldFilter     []byte
	Statuses        []string
	Authors         []uuid.UUID
	ExcludedAuthors []uuid.UUID
	Before          *time.Time
	After           *time.Time
	Search          string
}

type ListNestedContentRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
	AuthorName  string
}

func (q *Queries) ListNestedContent(ctx context.Context, arg ListNestedContentParams) ([]ListNestedContentRow, error) {
	rows, err := q.db.Query(ctx, listNestedContent,
		arg.RowOffset,
		arg.RowLimit,
		arg.OrderBy,
		arg.OrderDir,
		arg.Type,
		arg.FieldFilter,
		arg.Statuses,
		arg.Authors,
		arg.ExcludedAuthors,
		arg.Before,
		arg.After,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNestedContentRow
	for rows.Next() {
		var i ListNestedContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Path,
			&i.Fields,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedContent = `-- name: ListRelatedContent :many
SELECT c.id, c.type, c.status, c.slug, c.title, c.excerpt,
    c.author_id, c.published_at, c.created_at, c.updated_at, c.parent_id, c.path, c.fields
FROM (
    SELECT DISTINCT r.sort_at, r.from_id
    FROM core.content_relations r
    JOIN core.content pointing ON pointing.id = r.from_id
    JOIN core.content_types pointer ON pointer.key = pointing.type
    WHERE r.to_id = $1 AND r.visible AND pointer.active
    ORDER BY r.sort_at DESC, r.from_id
    LIMIT $3 OFFSET $2
) held
JOIN core.content c ON c.id = held.from_id
ORDER BY held.sort_at DESC, held.from_id
`

type ListRelatedContentParams struct {
	Target    uuid.UUID
	RowOffset int32
	RowLimit  int32
}

type ListRelatedContentRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
}

func (q *Queries) ListRelatedContent(ctx context.Context, arg ListRelatedContentParams) ([]ListRelatedContentRow, error) {
	rows, err := q.db.Query(ctx, listRelatedContent, arg.Target, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedContentRow
	for rows.Next() {
		var i ListRelatedContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Path,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.excerpt, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1
ORDER BY r.created_at DESC, r.id DESC
`

type ListRevisionsRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Excerpt   string
	CreatedAt time.Time
}

func (q *Queries) ListRevisions(ctx context.Context, contentID uuid.UUID) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.Kind,
			&i.AuthorID,
			&i.Title,
			&i.Excerpt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContent = `-- name: LockContent :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.id = $1
FOR UPDATE
`

func (q *Queries) LockContent(ctx context.Context, id uuid.UUID) (CoreContent, error) {
	row := q.db.QueryRow(ctx, lockContent, id)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const lockDeclaredFieldKeys = `-- name: LockDeclaredFieldKeys :many
SELECT key FROM core.content_fields ORDER BY key
FOR KEY SHARE
`

func (q *Queries) LockDeclaredFieldKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lockDeclaredFieldKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParent = `-- name: LockParent :one
WITH RECURSIVE chain AS (
    SELECT c.id, c.parent_id
    FROM core.content c
    WHERE c.id = $2
  UNION ALL
    SELECT up.id, up.parent_id
    FROM core.content up
    JOIN chain ON up.id = chain.parent_id
) CYCLE id SET looped USING trail
SELECT p.status, p.path,
    EXISTS (SELECT 1 FROM chain WHERE chain.id = $1::uuid AND NOT chain.looped) AS holds_child
FROM core.content p
WHERE p.id = $2
FOR KEY SHARE OF p
`

type LockParentParams struct {
	ChildID uuid.UUID
	ID      uuid.UUID
}

type LockParentRow struct {
	Status     string
	Path       string
	HoldsChild bool
}

func (q *Queries) LockParent(ctx context.Context, arg LockParentParams) (LockParentRow, error) {
	row := q.db.QueryRow(ctx, lockParent, arg.ChildID, arg.ID)
	var i LockParentRow
	err := row.Scan(&i.Status, &i.Path, &i.HoldsChild)
	return i, err
}

const lockTypeForMove = `-- name: LockTypeForMove :one
SELECT t.hierarchical FROM core.content_types t WHERE t.key = $1 FOR NO KEY UPDATE
`

func (q *Queries) LockTypeForMove(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, lockTypeForMove, key)
	var hierarchical bool
	err := row.Scan(&hierarchical)
	return hierarchical, err
}

const lockTypeNesting = `-- name: LockTypeNesting :one
SELECT t.hierarchical FROM core.content_types t WHERE t.key = $1 FOR SHARE
`

func (q *Queries) LockTypeNesting(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, lockTypeNesting, key)
	var hierarchical bool
	err := row.Scan(&hierarchical)
	return hierarchical, err
}

const moveDescendants = `-- name: MoveDescendants :exec
WITH RECURSIVE moved AS (
    SELECT c.id, $3::text AS path
    FROM core.content c
    WHERE c.id = $2
  UNION ALL
    SELECT child.id, moved.path || '/' || child.slug
    FROM core.content child
    JOIN moved ON child.parent_id = moved.id
) CYCLE id SET looped USING trail
UPDATE core.content AS p
SET path = moved.path, updated_at = $1
FROM moved
WHERE p.id = moved.id AND p.id <> $2
`

type MoveDescendantsParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
	Path      string
}

func (q *Queries) MoveDescendants(ctx context.Context, arg MoveDescendantsParams) error {
	_, err := q.db.Exec(ctx, moveDescendants, arg.UpdatedAt, arg.ID, arg.Path)
	return err
}

const pointingAt = `-- name: PointingAt :many
SELECT c.id, c.type, c.title, c.path
FROM (
    SELECT DISTINCT r.sort_at, r.from_id
    FROM core.content_relations r
    JOIN core.content pointing ON pointing.id = r.from_id
    JOIN core.content_types pointer ON pointer.key = pointing.type
    WHERE r.to_id = $1 AND r.field_id = $2 AND r.visible AND pointer.active
    ORDER BY r.sort_at DESC, r.from_id
    LIMIT $4 OFFSET $3
) held
JOIN core.content c ON c.id = held.from_id
ORDER BY held.sort_at DESC, held.from_id
`

type PointingAtParams struct {
	Target    uuid.UUID
	Field     int32
	RowOffset int32
	RowLimit  int32
}

type PointingAtRow struct {
	ID    uuid.UUID
	Type  string
	Title string
	Path  string
}

func (q *Queries) PointingAt(ctx context.Context, arg PointingAtParams) ([]PointingAtRow, error) {
	rows, err := q.db.Query(ctx, pointingAt,
		arg.Target,
		arg.Field,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointingAtRow
	for rows.Next() {
		var i PointingAtRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRevisions = `-- name: PruneRevisions :exec
DELETE FROM core.content_revisions AS r
WHERE r.id IN (
    SELECT p.id
    FROM core.content_revisions p
    WHERE p.content_id = $1 AND p.kind = 'revision'
    ORDER BY p.created_at DESC, p.id DESC
    OFFSET $2::int
)
`

type PruneRevisionsParams struct {
	ContentID uuid.UUID
	Keep      int32
}

func (q *Queries) PruneRevisions(ctx context.Context, arg PruneRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneRevisions, arg.ContentID, arg.Keep)
	return err
}

const refreshRelationVisibility = `-- name: RefreshRelationVisibility :exec
UPDATE core.content_relations r
SET sort_at = coalesce(c.published_at, c.created_at), visible = (c.status = 'published')
FROM core.content c
WHERE r.from_id = c.id AND c.id = $1
`

func (q *Queries) RefreshRelationVisibility(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshRelationVisibility, id)
	return err
}

const restoreContent = `-- name: RestoreContent :one
UPDATE core.content AS p
SET status = 'draft',
    slug = regexp_replace(p.slug, '-trashed-[a-z0-9]{8}$', ''),
    path = regexp_replace(p.path, '-trashed-[a-z0-9]{8}$', ''),
    updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type RestoreContentParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestoreContent(ctx context.Context, arg RestoreContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, restoreContent, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const restoreContentKeepingSlug = `-- name: RestoreContentKeepingSlug :one
UPDATE core.content AS p
SET status = 'draft', updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type RestoreContentKeepingSlugParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestoreContentKeepingSlug(ctx context.Context, arg RestoreContentKeepingSlugParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, restoreContentKeepingSlug, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const siblingSlugTaken = `-- name: SiblingSlugTaken :one
SELECT EXISTS (
    SELECT 1 FROM core.content p
    WHERE p.type = $1
        AND p.parent_id IS NOT DISTINCT FROM $2::uuid
        AND p.slug = $3
        AND p.id <> $4
)
`

type SiblingSlugTakenParams struct {
	Type     string
	ParentID *uuid.UUID
	Slug     string
	ID       uuid.UUID
}

func (q *Queries) SiblingSlugTaken(ctx context.Context, arg SiblingSlugTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, siblingSlugTaken,
		arg.Type,
		arg.ParentID,
		arg.Slug,
		arg.ID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const summariesOfTargets = `-- name: SummariesOfTargets :many
SELECT c.id, c.title, c.path
FROM core.content c
JOIN core.content_types t ON t.key = c.type
WHERE c.id = ANY($1::uuid []) AND c.status = 'published' AND t.active
`

type SummariesOfTargetsRow struct {
	ID    uuid.UUID
	Title string
	Path  string
}

func (q *Queries) SummariesOfTargets(ctx context.Context, ids []uuid.UUID) ([]SummariesOfTargetsRow, error) {
	rows, err := q.db.Query(ctx, summariesOfTargets, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummariesOfTargetsRow
	for rows.Next() {
		var i SummariesOfTargetsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashContent = `-- name: TrashContent :one
UPDATE core.content AS p
SET status = 'trash', slug = p.slug || $1::text, path = p.path || $1::text,
    updated_at = $2
WHERE p.id = $3
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type TrashContentParams struct {
	Suffix    string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) TrashContent(ctx context.Context, arg TrashContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, trashContent, arg.Suffix, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const typesOfContent = `-- name: TypesOfContent :many
SELECT id, type FROM core.content WHERE id = ANY($1::uuid[])
`

type TypesOfContentRow struct {
	ID   uuid.UUID
	Type string
}

func (q *Queries) TypesOfContent(ctx context.Context, ids []uuid.UUID) ([]TypesOfContentRow, error) {
	rows, err := q.db.Query(ctx, typesOfContent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypesOfContentRow
	for rows.Next() {
		var i TypesOfContentRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE core.content AS p
SET status = $1, slug = $2, path = $3, parent_id = $4, title = $5,
    content = $6, excerpt = $7, fields = $8, published_at = $9,
    updated_at = $10
WHERE p.id = $11 AND p.updated_at = $12
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type UpdateContentParams struct {
	Status            string
	Slug              string
	Path              string
	ParentID          *uuid.UUID
	Title             string
	Content           string
	Excerpt           string
	Fields            content.Values
	PublishedAt       *time.Time
	UpdatedAt         time.Time
	ID                uuid.UUID
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, updateContent,
		arg.Status,
		arg.Slug,
		arg.Path,
		arg.ParentID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const upsertAutosave = `-- name: UpsertAutosave :one
INSERT INTO core.content_revisions (
    id, content_id, kind, author_id, title, content, excerpt, fields, created_at
)
VALUES (
    $1, $2, 'autosave', $3, $4, $5, $6, $7, $8
)
ON CONFLICT (content_id, author_id) WHERE kind = 'autosave'
DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    excerpt = EXCLUDED.excerpt,
    fields = EXCLUDED.fields,
    created_at = EXCLUDED.created_at
RETURNING id, content_id, kind, author_id, title, content, excerpt, fields, created_at
`

type UpsertAutosaveParams struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

type UpsertAutosaveRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) UpsertAutosave(ctx context.Context, arg UpsertAutosaveParams) (UpsertAutosaveRow, error) {
	row := q.db.QueryRow(ctx, upsertAutosave,
		arg.ID,
		arg.ContentID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.CreatedAt,
	)
	var i UpsertAutosaveRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const valuesOfContent = `-- name: ValuesOfContent :one
SELECT fields FROM core.content WHERE id = $1
`

func (q *Queries) ValuesOfContent(ctx context.Context, id uuid.UUID) (content.Values, error) {
	row := q.db.QueryRow(ctx, valuesOfContent, id)
	var fields content.Values
	err := row.Scan(&fields)
	return fields, err
}
