// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type CorePost struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
