// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/gopherium/gophenberg/internal/content"
	"github.com/gopherium/gophenberg/internal/media"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreContent struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
}

type CoreContentField struct {
	ID            int32
	Key           string
	Label         string
	Kind          string
	RelatesTo     *string
	Many          bool
	Required      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Position      int32
	GroupID       int32
	Settings      []byte
	ParentFieldID pgtype.Int4
}

type CoreContentRelation struct {
	FromID   uuid.UUID
	FieldID  int32
	ToID     uuid.UUID
	Position int32
	SortAt   time.Time
	Visible  bool
}

type CoreContentRevision struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	CreatedAt time.Time
	Fields    content.Values
}

type CoreContentType struct {
	Key           string
	SingularLabel string
	PluralLabel   string
	RouteWord     string
	Hierarchical  bool
	Revisions     bool
	RevisionCap   int32
	PageKind      string
	IsDefault     bool
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type CoreFieldGroup struct {
	ID        int32
	Title     string
	Location  []byte
	Position  int32
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CoreMedia struct {
	ID          int64
	MediaType   string
	File        string
	Title       string
	AltText     string
	Caption     string
	Description string
	MimeType    string
	Width       int32
	Height      int32
	Filesize    int64
	Sizes       media.RenditionMap
	AuthorID    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CoreSetting struct {
	Key   string
	Value string
}

type CoreUserSetting struct {
	UserID uuid.UUID
	Key    string
	Value  string
}
