// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/gopherium/gophenberg/internal/content"
	"github.com/gopherium/gophenberg/internal/media"
)

const addRelation = `-- name: AddRelation :exec
INSERT INTO core.content_relations (from_id, field_id, to_id, position, sort_at, visible)
SELECT $1, $2, $3, $4, coalesce(c.published_at, c.created_at),
    c.status = 'published'
FROM core.content c
WHERE c.id = $1
`

type AddRelationParams struct {
	FromID   uuid.UUID
	FieldID  int32
	ToID     uuid.UUID
	Position int32
}

func (q *Queries) AddRelation(ctx context.Context, arg AddRelationParams) error {
	_, err := q.db.Exec(ctx, addRelation,
		arg.FromID,
		arg.FieldID,
		arg.ToID,
		arg.Position,
	)
	return err
}

const clearContentFieldValues = `-- name: ClearContentFieldValues :exec
UPDATE core.content SET fields = fields - $1::text
WHERE type = ANY($2::text []) AND fields ? $1::text
`

type ClearContentFieldValuesParams struct {
	Key   string
	Types []string
}

func (q *Queries) ClearContentFieldValues(ctx context.Context, arg ClearContentFieldValuesParams) error {
	_, err := q.db.Exec(ctx, clearContentFieldValues, arg.Key, arg.Types)
	return err
}

const clearRelationsOfField = `-- name: ClearRelationsOfField :exec
DELETE FROM core.content_relations WHERE from_id = $1 AND field_id = $2
`

type ClearRelationsOfFieldParams struct {
	FromID  uuid.UUID
	FieldID int32
}

func (q *Queries) ClearRelationsOfField(ctx context.Context, arg ClearRelationsOfFieldParams) error {
	_, err := q.db.Exec(ctx, clearRelationsOfField, arg.FromID, arg.FieldID)
	return err
}

const clearRevisionFieldValues = `-- name: ClearRevisionFieldValues :exec
UPDATE core.content_revisions r
SET fields = r.fields - $1::text
FROM core.content c
WHERE r.content_id = c.id AND c.type = ANY($2::text []) AND r.fields ? $1::text
`

type ClearRevisionFieldValuesParams struct {
	Key   string
	Types []string
}

func (q *Queries) ClearRevisionFieldValues(ctx context.Context, arg ClearRevisionFieldValuesParams) error {
	_, err := q.db.Exec(ctx, clearRevisionFieldValues, arg.Key, arg.Types)
	return err
}

const contentDepth = `-- name: ContentDepth :one
WITH RECURSIVE below AS (
    SELECT c.id, 0 AS level
    FROM core.content c
    WHERE c.id = $1
    UNION ALL
    SELECT child.id, below.level + 1
    FROM core.content child
    JOIN below ON child.parent_id = below.id
)
SELECT coalesce(max(level), 0)::int FROM below
`

func (q *Queries) ContentDepth(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, contentDepth, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM core.content p WHERE p.parent_id = $1
`

func (q *Queries) CountChildren(ctx context.Context, id *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContent = `-- name: CountContent :one
SELECT count(*)
FROM core.content p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
`

type CountContentParams struct {
	Type   string
	Status string
	Search string
}

func (q *Queries) CountContent(ctx context.Context, arg CountContentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContent, arg.Type, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContentByStatus = `-- name: CountContentByStatus :many
SELECT p.status, count(*) AS total
FROM core.content p
WHERE p.type = $1
GROUP BY p.status
`

type CountContentByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountContentByStatus(ctx context.Context, type_ string) ([]CountContentByStatusRow, error) {
	rows, err := q.db.Query(ctx, countContentByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountContentByStatusRow
	for rows.Next() {
		var i CountContentByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMedia = `-- name: CountMedia :one
SELECT count(*)
FROM core.media m
WHERE ($1::text = '' OR m.media_type = $1)
    AND (
        cardinality($2::text[]) = 0
        OR EXISTS (
            SELECT 1 FROM unnest($2::text[]) AS prefix
            WHERE m.mime_type LIKE prefix || '%'
        )
    )
    AND (
        $3::text = ''
        OR m.title ILIKE '%' || $3 || '%'
        OR m.file ILIKE '%' || $3 || '%'
    )
`

type CountMediaParams struct {
	MediaType string
	Mimes     []string
	Search    string
}

func (q *Queries) CountMedia(ctx context.Context, arg CountMediaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia, arg.MediaType, arg.Mimes, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelatedContent = `-- name: CountRelatedContent :one
SELECT count(DISTINCT r.from_id)
FROM core.content_relations r
JOIN core.content c ON c.id = r.from_id
JOIN core.content_types t ON t.key = c.type
WHERE r.to_id = $1 AND r.visible AND t.active
`

func (q *Queries) CountRelatedContent(ctx context.Context, target uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelatedContent, target)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContent = `-- name: CreateContent :one

INSERT INTO core.content (
    id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at, parent_id, path
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
RETURNING id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at, parent_id, path, fields
`

type CreateContentParams struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.AuthorID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ParentID,
		arg.Path,
	)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const createContentField = `-- name: CreateContentField :one
INSERT INTO core.content_fields (
    group_id, key, label, kind, relates_to, many, required, position, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM core.content_fields WHERE group_id = $1),
    $8, $9
)
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id
`

type CreateContentFieldParams struct {
	GroupID   int32
	Key       string
	Label     string
	Kind      string
	RelatesTo *string
	Many      bool
	Required  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateContentField(ctx context.Context, arg CreateContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, createContentField,
		arg.GroupID,
		arg.Key,
		arg.Label,
		arg.Kind,
		arg.RelatesTo,
		arg.Many,
		arg.Required,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
	)
	return i, err
}

const createContentType = `-- name: CreateContentType :one
INSERT INTO core.content_types (
    key, singular_label, plural_label, route_word, hierarchical, revisions,
    revision_cap, page_kind, is_default, active, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING key, singular_label, plural_label, route_word, hierarchical, revisions,
    revision_cap, page_kind, is_default, active, created_at, updated_at
`

type CreateContentTypeParams struct {
	Key           string
	SingularLabel string
	PluralLabel   string
	RouteWord     string
	Hierarchical  bool
	Revisions     bool
	RevisionCap   int32
	PageKind      string
	IsDefault     bool
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateContentType(ctx context.Context, arg CreateContentTypeParams) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, createContentType,
		arg.Key,
		arg.SingularLabel,
		arg.PluralLabel,
		arg.RouteWord,
		arg.Hierarchical,
		arg.Revisions,
		arg.RevisionCap,
		arg.PageKind,
		arg.IsDefault,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFieldGroup = `-- name: CreateFieldGroup :one
INSERT INTO core.field_groups (title, location, position, created_at, updated_at)
VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM core.field_groups),
    $3, $4
)
RETURNING id, title, location, position, active, created_at, updated_at
`

type CreateFieldGroupParams struct {
	Title     string
	Location  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFieldGroup(ctx context.Context, arg CreateFieldGroupParams) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, createFieldGroup,
		arg.Title,
		arg.Location,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO core.media (
    media_type, file, title, alt_text, caption, description,
    mime_type, width, height, filesize, sizes, author_id, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, media_type, file, title, alt_text, caption, description,
    mime_type, width, height, filesize, sizes, author_id, created_at, updated_at
`

type CreateMediaParams struct {
	MediaType   string
	File        string
	Title       string
	AltText     string
	Caption     string
	Description string
	MimeType    string
	Width       int32
	Height      int32
	Filesize    int64
	Sizes       media.RenditionMap
	AuthorID    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.MediaType,
		arg.File,
		arg.Title,
		arg.AltText,
		arg.Caption,
		arg.Description,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.Filesize,
		arg.Sizes,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO core.content_revisions (
    id, content_id, kind, author_id, title, content, excerpt, fields, created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateRevisionParams struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.Exec(ctx, createRevision,
		arg.ID,
		arg.ContentID,
		arg.Kind,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.CreatedAt,
	)
	return err
}

const deleteAutosave = `-- name: DeleteAutosave :exec
DELETE FROM core.content_revisions AS r
WHERE r.content_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type DeleteAutosaveParams struct {
	ContentID uuid.UUID
	AuthorID  uuid.UUID
}

func (q *Queries) DeleteAutosave(ctx context.Context, arg DeleteAutosaveParams) error {
	_, err := q.db.Exec(ctx, deleteAutosave, arg.ContentID, arg.AuthorID)
	return err
}

const deleteContent = `-- name: DeleteContent :execrows
DELETE FROM core.content AS p WHERE p.id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContentField = `-- name: DeleteContentField :execrows
DELETE FROM core.content_fields WHERE group_id = $1 AND key = $2
`

type DeleteContentFieldParams struct {
	GroupID int32
	Key     string
}

func (q *Queries) DeleteContentField(ctx context.Context, arg DeleteContentFieldParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContentField, arg.GroupID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContentType = `-- name: DeleteContentType :execrows
DELETE FROM core.content_types AS t WHERE t.key = $1
`

func (q *Queries) DeleteContentType(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContentType, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFieldGroup = `-- name: DeleteFieldGroup :execrows
DELETE FROM core.field_groups WHERE id = $1
`

func (q *Queries) DeleteFieldGroup(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFieldGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMedia = `-- name: DeleteMedia :one
DELETE FROM core.media AS m
WHERE m.id = $1
RETURNING m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, deleteMedia, id)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRevision = `-- name: DeleteRevision :execrows
DELETE FROM core.content_revisions AS r
WHERE r.content_id = $1 AND r.id = $2
`

type DeleteRevisionParams struct {
	ContentID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteRevision(ctx context.Context, arg DeleteRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevision, arg.ContentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAutosave = `-- name: GetAutosave :one
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.fields, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type GetAutosaveParams struct {
	ContentID uuid.UUID
	AuthorID  uuid.UUID
}

type GetAutosaveRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) GetAutosave(ctx context.Context, arg GetAutosaveParams) (GetAutosaveRow, error) {
	row := q.db.QueryRow(ctx, getAutosave, arg.ContentID, arg.AuthorID)
	var i GetAutosaveRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const getContent = `-- name: GetContent :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.id = $1
`

func (q *Queries) GetContent(ctx context.Context, id uuid.UUID) (CoreContent, error) {
	row := q.db.QueryRow(ctx, getContent, id)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const getContentType = `-- name: GetContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at
FROM core.content_types t
WHERE t.key = $1
`

func (q *Queries) GetContentType(ctx context.Context, key string) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, getContentType, key)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
FROM core.media m
WHERE m.id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedContentByPath = `-- name: GetPublishedContentByPath :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.path = $1 AND p.status = 'published'
`

func (q *Queries) GetPublishedContentByPath(ctx context.Context, path string) (CoreContent, error) {
	row := q.db.QueryRow(ctx, getPublishedContentByPath, path)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.fields, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1 AND r.id = $2
`

type GetRevisionParams struct {
	ContentID uuid.UUID
	ID        uuid.UUID
}

type GetRevisionRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (GetRevisionRow, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.ContentID, arg.ID)
	var i GetRevisionRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT s.value FROM core.settings s WHERE s.key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT u.value FROM core.user_settings u WHERE u.user_id = $1 AND u.key = $2
`

type GetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserSetting, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const groupByLocation = `-- name: GroupByLocation :one
SELECT id, title, location, position, active, created_at, updated_at
FROM core.field_groups WHERE location = $1
ORDER BY position, id LIMIT 1
`

func (q *Queries) GroupByLocation(ctx context.Context, location []byte) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, groupByLocation, location)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContent = `-- name: ListContent :many
SELECT p.id, p.type, p.status, p.slug, p.title, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
ORDER BY
    CASE WHEN $4::text = 'title' AND $5::text = 'asc' THEN p.title END ASC,
    CASE WHEN $4::text = 'title' AND $5::text = 'desc' THEN p.title END DESC,
    CASE WHEN $4::text <> 'title' AND $5::text = 'asc'
        THEN COALESCE(p.published_at, p.created_at) END ASC,
    CASE WHEN $4::text <> 'title' AND $5::text <> 'asc'
        THEN COALESCE(p.published_at, p.created_at) END DESC,
    p.id DESC
LIMIT $7 OFFSET $6
`

type ListContentParams struct {
	Type      string
	Status    string
	Search    string
	OrderBy   string
	OrderDir  string
	RowOffset int32
	RowLimit  int32
}

type ListContentRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
}

func (q *Queries) ListContent(ctx context.Context, arg ListContentParams) ([]ListContentRow, error) {
	rows, err := q.db.Query(ctx, listContent,
		arg.Type,
		arg.Status,
		arg.Search,
		arg.OrderBy,
		arg.OrderDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentRow
	for rows.Next() {
		var i ListContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Path,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentFields = `-- name: ListContentFields :many
SELECT id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id
FROM core.content_fields ORDER BY group_id, position, id
`

func (q *Queries) ListContentFields(ctx context.Context) ([]CoreContentField, error) {
	rows, err := q.db.Query(ctx, listContentFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentField
	for rows.Next() {
		var i CoreContentField
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Kind,
			&i.RelatesTo,
			&i.Many,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentFieldsOfGroup = `-- name: ListContentFieldsOfGroup :many
SELECT id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id
FROM core.content_fields WHERE group_id = $1 ORDER BY position, id
`

func (q *Queries) ListContentFieldsOfGroup(ctx context.Context, groupID int32) ([]CoreContentField, error) {
	rows, err := q.db.Query(ctx, listContentFieldsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentField
	for rows.Next() {
		var i CoreContentField
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Kind,
			&i.RelatesTo,
			&i.Many,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentTypes = `-- name: ListContentTypes :many
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at
FROM core.content_types t
ORDER BY t.created_at, t.key
`

func (q *Queries) ListContentTypes(ctx context.Context) ([]CoreContentType, error) {
	rows, err := q.db.Query(ctx, listContentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentType
	for rows.Next() {
		var i CoreContentType
		if err := rows.Scan(
			&i.Key,
			&i.SingularLabel,
			&i.PluralLabel,
			&i.RouteWord,
			&i.Hierarchical,
			&i.Revisions,
			&i.RevisionCap,
			&i.PageKind,
			&i.IsDefault,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldGroups = `-- name: ListFieldGroups :many
SELECT id, title, location, position, active, created_at, updated_at
FROM core.field_groups ORDER BY position, id
`

func (q *Queries) ListFieldGroups(ctx context.Context) ([]CoreFieldGroup, error) {
	rows, err := q.db.Query(ctx, listFieldGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreFieldGroup
	for rows.Next() {
		var i CoreFieldGroup
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
FROM core.media m
WHERE ($1::text = '' OR m.media_type = $1)
    AND (
        cardinality($2::text[]) = 0
        OR EXISTS (
            SELECT 1 FROM unnest($2::text[]) AS prefix
            WHERE m.mime_type LIKE prefix || '%'
        )
    )
    AND (
        $3::text = ''
        OR m.title ILIKE '%' || $3 || '%'
        OR m.file ILIKE '%' || $3 || '%'
    )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5 OFFSET $4
`

type ListMediaParams struct {
	MediaType string
	Mimes     []string
	Search    string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]CoreMedia, error) {
	rows, err := q.db.Query(ctx, listMedia,
		arg.MediaType,
		arg.Mimes,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreMedia
	for rows.Next() {
		var i CoreMedia
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.File,
			&i.Title,
			&i.AltText,
			&i.Caption,
			&i.Description,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Filesize,
			&i.Sizes,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedContent = `-- name: ListRelatedContent :many
SELECT c.id, c.type, c.status, c.slug, c.title, c.excerpt,
    c.author_id, c.published_at, c.created_at, c.updated_at, c.parent_id, c.path, c.fields
FROM (
    SELECT DISTINCT r.sort_at, r.from_id
    FROM core.content_relations r
    JOIN core.content pointing ON pointing.id = r.from_id
    JOIN core.content_types pointer ON pointer.key = pointing.type
    WHERE r.to_id = $1 AND r.visible AND pointer.active
    ORDER BY r.sort_at DESC, r.from_id
    LIMIT $3 OFFSET $2
) held
JOIN core.content c ON c.id = held.from_id
ORDER BY held.sort_at DESC, held.from_id
`

type ListRelatedContentParams struct {
	Target    uuid.UUID
	RowOffset int32
	RowLimit  int32
}

type ListRelatedContentRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ParentID    *uuid.UUID
	Path        string
	Fields      content.Values
}

func (q *Queries) ListRelatedContent(ctx context.Context, arg ListRelatedContentParams) ([]ListRelatedContentRow, error) {
	rows, err := q.db.Query(ctx, listRelatedContent, arg.Target, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedContentRow
	for rows.Next() {
		var i ListRelatedContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Path,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationFieldsOfGroups = `-- name: ListRelationFieldsOfGroups :many
SELECT id, key, relates_to, many FROM core.content_fields
WHERE group_id = ANY($1::integer []) AND kind = 'relation'
ORDER BY id
`

type ListRelationFieldsOfGroupsRow struct {
	ID        int32
	Key       string
	RelatesTo *string
	Many      bool
}

func (q *Queries) ListRelationFieldsOfGroups(ctx context.Context, ids []int32) ([]ListRelationFieldsOfGroupsRow, error) {
	rows, err := q.db.Query(ctx, listRelationFieldsOfGroups, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationFieldsOfGroupsRow
	for rows.Next() {
		var i ListRelationFieldsOfGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.RelatesTo,
			&i.Many,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationSummaries = `-- name: ListRelationSummaries :many
SELECT f.key, c.id, c.title, c.path
FROM core.content_relations r
JOIN core.content_fields f ON f.id = r.field_id
JOIN core.content c ON c.id = r.to_id
JOIN core.content_types t ON t.key = c.type
WHERE r.from_id = $1 AND c.status = 'published' AND t.active
ORDER BY f.key, r.position
`

type ListRelationSummariesRow struct {
	Key   string
	ID    uuid.UUID
	Title string
	Path  string
}

func (q *Queries) ListRelationSummaries(ctx context.Context, fromID uuid.UUID) ([]ListRelationSummariesRow, error) {
	rows, err := q.db.Query(ctx, listRelationSummaries, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationSummariesRow
	for rows.Next() {
		var i ListRelationSummariesRow
		if err := rows.Scan(
			&i.Key,
			&i.ID,
			&i.Title,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTargets = `-- name: ListRelationTargets :many
SELECT f.key, r.to_id
FROM core.content_relations r
JOIN core.content_fields f ON f.id = r.field_id
WHERE r.from_id = $1
ORDER BY f.key, r.position
`

type ListRelationTargetsRow struct {
	Key  string
	ToID uuid.UUID
}

func (q *Queries) ListRelationTargets(ctx context.Context, fromID uuid.UUID) ([]ListRelationTargetsRow, error) {
	rows, err := q.db.Query(ctx, listRelationTargets, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationTargetsRow
	for rows.Next() {
		var i ListRelationTargetsRow
		if err := rows.Scan(&i.Key, &i.ToID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.content_id, r.kind, r.author_id, r.title, r.excerpt, r.created_at
FROM core.content_revisions r
WHERE r.content_id = $1
ORDER BY r.created_at DESC, r.id DESC
`

type ListRevisionsRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Excerpt   string
	CreatedAt time.Time
}

func (q *Queries) ListRevisions(ctx context.Context, contentID uuid.UUID) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.Kind,
			&i.AuthorID,
			&i.Title,
			&i.Excerpt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContent = `-- name: LockContent :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
FROM core.content p
WHERE p.id = $1
FOR UPDATE
`

func (q *Queries) LockContent(ctx context.Context, id uuid.UUID) (CoreContent, error) {
	row := q.db.QueryRow(ctx, lockContent, id)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const lockContentType = `-- name: LockContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at
FROM core.content_types t
WHERE t.key = $1
FOR UPDATE
`

func (q *Queries) LockContentType(ctx context.Context, key string) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, lockContentType, key)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDeclaredFieldKeys = `-- name: LockDeclaredFieldKeys :many
SELECT key FROM core.content_fields ORDER BY key
FOR KEY SHARE
`

func (q *Queries) LockDeclaredFieldKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lockDeclaredFieldKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDefaultContentType = `-- name: LockDefaultContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at
FROM core.content_types t
WHERE t.is_default
FOR UPDATE
`

func (q *Queries) LockDefaultContentType(ctx context.Context) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, lockDefaultContentType)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFieldGroups = `-- name: LockFieldGroups :exec
SELECT pg_advisory_xact_lock(hashtext('core.field_groups'))
`

func (q *Queries) LockFieldGroups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockFieldGroups)
	return err
}

const moveContentField = `-- name: MoveContentField :one
UPDATE core.content_fields AS moved
SET group_id = $1,
    position = (
        SELECT COALESCE(MAX(landing.position), 0) + 1
        FROM core.content_fields AS landing WHERE landing.group_id = $1
    ),
    updated_at = $2
WHERE moved.group_id = $3 AND moved.key = $4
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id
`

type MoveContentFieldParams struct {
	ToGroup   int32
	UpdatedAt time.Time
	GroupID   int32
	Key       string
}

func (q *Queries) MoveContentField(ctx context.Context, arg MoveContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, moveContentField,
		arg.ToGroup,
		arg.UpdatedAt,
		arg.GroupID,
		arg.Key,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
	)
	return i, err
}

const moveDescendants = `-- name: MoveDescendants :exec
WITH RECURSIVE moved AS (
    SELECT c.id, $3::text AS path
    FROM core.content c
    WHERE c.id = $2
  UNION ALL
    SELECT child.id, moved.path || '/' || child.slug
    FROM core.content child
    JOIN moved ON child.parent_id = moved.id
) CYCLE id SET looped USING trail
UPDATE core.content AS p
SET path = moved.path, updated_at = $1
FROM moved
WHERE p.id = moved.id AND p.id <> $2
`

type MoveDescendantsParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
	Path      string
}

func (q *Queries) MoveDescendants(ctx context.Context, arg MoveDescendantsParams) error {
	_, err := q.db.Exec(ctx, moveDescendants, arg.UpdatedAt, arg.ID, arg.Path)
	return err
}

const pruneRevisions = `-- name: PruneRevisions :exec
DELETE FROM core.content_revisions AS r
WHERE r.id IN (
    SELECT p.id
    FROM core.content_revisions p
    WHERE p.content_id = $1 AND p.kind = 'revision'
    ORDER BY p.created_at DESC, p.id DESC
    OFFSET $2::int
)
`

type PruneRevisionsParams struct {
	ContentID uuid.UUID
	Keep      int32
}

func (q *Queries) PruneRevisions(ctx context.Context, arg PruneRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneRevisions, arg.ContentID, arg.Keep)
	return err
}

const refreshRelationVisibility = `-- name: RefreshRelationVisibility :exec
UPDATE core.content_relations r
SET sort_at = coalesce(c.published_at, c.created_at), visible = (c.status = 'published')
FROM core.content c
WHERE r.from_id = c.id AND c.id = $1
`

func (q *Queries) RefreshRelationVisibility(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshRelationVisibility, id)
	return err
}

const reorderContentFields = `-- name: ReorderContentFields :exec
UPDATE core.content_fields
SET position = ordered.position
FROM (
    SELECT key, ordinality AS position
    FROM unnest($2::text []) WITH ORDINALITY AS asked (key, ordinality)
) AS ordered
WHERE core.content_fields.group_id = $1 AND core.content_fields.key = ordered.key
`

type ReorderContentFieldsParams struct {
	GroupID int32
	Keys    []string
}

func (q *Queries) ReorderContentFields(ctx context.Context, arg ReorderContentFieldsParams) error {
	_, err := q.db.Exec(ctx, reorderContentFields, arg.GroupID, arg.Keys)
	return err
}

const reorderFieldGroups = `-- name: ReorderFieldGroups :exec
UPDATE core.field_groups
SET position = ordered.position
FROM (
    SELECT id, ordinality AS position
    FROM unnest($1::integer []) WITH ORDINALITY AS asked (id, ordinality)
) AS ordered
WHERE core.field_groups.id = ordered.id
`

func (q *Queries) ReorderFieldGroups(ctx context.Context, ids []int32) error {
	_, err := q.db.Exec(ctx, reorderFieldGroups, ids)
	return err
}

const restoreContent = `-- name: RestoreContent :one
UPDATE core.content AS p
SET status = 'draft',
    slug = regexp_replace(p.slug, '-trashed-[a-z0-9]{8}$', ''),
    path = regexp_replace(p.path, '-trashed-[a-z0-9]{8}$', ''),
    updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type RestoreContentParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestoreContent(ctx context.Context, arg RestoreContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, restoreContent, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const restoreContentKeepingSlug = `-- name: RestoreContentKeepingSlug :one
UPDATE core.content AS p
SET status = 'draft', updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type RestoreContentKeepingSlugParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestoreContentKeepingSlug(ctx context.Context, arg RestoreContentKeepingSlugParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, restoreContentKeepingSlug, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const retypeContentPaths = `-- name: RetypeContentPaths :exec
UPDATE core.content c
SET path = trim(leading '/' from $1::text || '/' ||
        CASE WHEN $2::text = '' THEN c.path
            ELSE substring(c.path from length($2::text) + 2) END),
    updated_at = $3
WHERE c.type = $4
`

type RetypeContentPathsParams struct {
	RouteWord string
	Was       string
	UpdatedAt time.Time
	Key       string
}

func (q *Queries) RetypeContentPaths(ctx context.Context, arg RetypeContentPathsParams) error {
	_, err := q.db.Exec(ctx, retypeContentPaths,
		arg.RouteWord,
		arg.Was,
		arg.UpdatedAt,
		arg.Key,
	)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO core.settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.Exec(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const setUserSetting = `-- name: SetUserSetting :exec
INSERT INTO core.user_settings (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value
`

type SetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
	Value  string
}

func (q *Queries) SetUserSetting(ctx context.Context, arg SetUserSettingParams) error {
	_, err := q.db.Exec(ctx, setUserSetting, arg.UserID, arg.Key, arg.Value)
	return err
}

const siblingSlugTaken = `-- name: SiblingSlugTaken :one
SELECT EXISTS (
    SELECT 1 FROM core.content p
    WHERE p.type = $1
        AND p.parent_id IS NOT DISTINCT FROM $2::uuid
        AND p.slug = $3
        AND p.id <> $4
)
`

type SiblingSlugTakenParams struct {
	Type     string
	ParentID *uuid.UUID
	Slug     string
	ID       uuid.UUID
}

func (q *Queries) SiblingSlugTaken(ctx context.Context, arg SiblingSlugTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, siblingSlugTaken,
		arg.Type,
		arg.ParentID,
		arg.Slug,
		arg.ID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const trashContent = `-- name: TrashContent :one
UPDATE core.content AS p
SET status = 'trash', slug = p.slug || $1::text, path = p.path || $1::text,
    updated_at = $2
WHERE p.id = $3
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type TrashContentParams struct {
	Suffix    string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) TrashContent(ctx context.Context, arg TrashContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, trashContent, arg.Suffix, arg.UpdatedAt, arg.ID)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const typeKeys = `-- name: TypeKeys :many
SELECT key FROM core.content_types ORDER BY created_at, key
`

func (q *Queries) TypeKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, typeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const typesOfContent = `-- name: TypesOfContent :many
SELECT id, type FROM core.content WHERE id = ANY($1::uuid[])
`

type TypesOfContentRow struct {
	ID   uuid.UUID
	Type string
}

func (q *Queries) TypesOfContent(ctx context.Context, ids []uuid.UUID) ([]TypesOfContentRow, error) {
	rows, err := q.db.Query(ctx, typesOfContent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypesOfContentRow
	for rows.Next() {
		var i TypesOfContentRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE core.content AS p
SET status = $1, slug = $2, path = $3, parent_id = $4, title = $5,
    content = $6, excerpt = $7, fields = $8, published_at = $9,
    updated_at = $10
WHERE p.id = $11 AND p.updated_at = $12
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at, p.parent_id, p.path, p.fields
`

type UpdateContentParams struct {
	Status            string
	Slug              string
	Path              string
	ParentID          *uuid.UUID
	Title             string
	Content           string
	Excerpt           string
	Fields            content.Values
	PublishedAt       *time.Time
	UpdatedAt         time.Time
	ID                uuid.UUID
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (CoreContent, error) {
	row := q.db.QueryRow(ctx, updateContent,
		arg.Status,
		arg.Slug,
		arg.Path,
		arg.ParentID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CoreContent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Path,
		&i.Fields,
	)
	return i, err
}

const updateContentField = `-- name: UpdateContentField :one
UPDATE core.content_fields
SET label = $1, required = $2, updated_at = $3
WHERE group_id = $4 AND key = $5
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id
`

type UpdateContentFieldParams struct {
	Label     string
	Required  bool
	UpdatedAt time.Time
	GroupID   int32
	Key       string
}

func (q *Queries) UpdateContentField(ctx context.Context, arg UpdateContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, updateContentField,
		arg.Label,
		arg.Required,
		arg.UpdatedAt,
		arg.GroupID,
		arg.Key,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
	)
	return i, err
}

const updateContentType = `-- name: UpdateContentType :one
UPDATE core.content_types AS t
SET singular_label = $1, plural_label = $2, route_word = $3,
    hierarchical = $4, revisions = $5, revision_cap = $6,
    page_kind = $7, is_default = $8, active = $9, updated_at = $10
WHERE t.key = $11
RETURNING t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at
`

type UpdateContentTypeParams struct {
	SingularLabel string
	PluralLabel   string
	RouteWord     string
	Hierarchical  bool
	Revisions     bool
	RevisionCap   int32
	PageKind      string
	IsDefault     bool
	Active        bool
	UpdatedAt     time.Time
	Key           string
}

func (q *Queries) UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, updateContentType,
		arg.SingularLabel,
		arg.PluralLabel,
		arg.RouteWord,
		arg.Hierarchical,
		arg.Revisions,
		arg.RevisionCap,
		arg.PageKind,
		arg.IsDefault,
		arg.Active,
		arg.UpdatedAt,
		arg.Key,
	)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFieldGroup = `-- name: UpdateFieldGroup :one
UPDATE core.field_groups
SET title = $1, location = $2, active = $3, updated_at = $4
WHERE id = $5
RETURNING id, title, location, position, active, created_at, updated_at
`

type UpdateFieldGroupParams struct {
	Title     string
	Location  []byte
	Active    bool
	UpdatedAt time.Time
	ID        int32
}

func (q *Queries) UpdateFieldGroup(ctx context.Context, arg UpdateFieldGroupParams) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, updateFieldGroup,
		arg.Title,
		arg.Location,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE core.media AS m
SET title = $1, alt_text = $2, caption = $3,
    description = $4, updated_at = $5
WHERE m.id = $6 AND m.updated_at = $7
RETURNING m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
`

type UpdateMediaParams struct {
	Title             string
	AltText           string
	Caption           string
	Description       string
	UpdatedAt         time.Time
	ID                int64
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, updateMedia,
		arg.Title,
		arg.AltText,
		arg.Caption,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAutosave = `-- name: UpsertAutosave :one
INSERT INTO core.content_revisions (
    id, content_id, kind, author_id, title, content, excerpt, fields, created_at
)
VALUES (
    $1, $2, 'autosave', $3, $4, $5, $6, $7, $8
)
ON CONFLICT (content_id, author_id) WHERE kind = 'autosave'
DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    excerpt = EXCLUDED.excerpt,
    fields = EXCLUDED.fields,
    created_at = EXCLUDED.created_at
RETURNING id, content_id, kind, author_id, title, content, excerpt, fields, created_at
`

type UpsertAutosaveParams struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

type UpsertAutosaveRow struct {
	ID        uuid.UUID
	ContentID uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	Fields    content.Values
	CreatedAt time.Time
}

func (q *Queries) UpsertAutosave(ctx context.Context, arg UpsertAutosaveParams) (UpsertAutosaveRow, error) {
	row := q.db.QueryRow(ctx, upsertAutosave,
		arg.ID,
		arg.ContentID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Fields,
		arg.CreatedAt,
	)
	var i UpsertAutosaveRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}
