// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*)
FROM core.posts p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
`

type CountPostsParams struct {
	Type   string
	Status string
	Search string
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, arg.Type, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByStatus = `-- name: CountPostsByStatus :many
SELECT p.status, count(*) AS total
FROM core.posts p
WHERE p.type = $1
GROUP BY p.status
`

type CountPostsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountPostsByStatus(ctx context.Context, type_ string) ([]CountPostsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countPostsByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPostsByStatusRow
	for rows.Next() {
		var i CountPostsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPost = `-- name: CreatePost :exec

INSERT INTO core.posts (
    id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
`

type CreatePostParams struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.AuthorID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM core.posts AS p WHERE p.id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
FROM core.posts p
WHERE p.id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (CorePost, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.type, p.status, p.slug, p.title, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
FROM core.posts p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
ORDER BY COALESCE(p.published_at, p.created_at) DESC, p.id DESC
LIMIT $5 OFFSET $4
`

type ListPostsParams struct {
	Type      string
	Status    string
	Search    string
	RowOffset int32
	RowLimit  int32
}

type ListPostsRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Type,
		arg.Status,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePost = `-- name: RestorePost :execrows
UPDATE core.posts AS p
SET status = 'draft',
    slug = regexp_replace(p.slug, '-trashed-[a-z0-9]{8}$', ''),
    updated_at = $1
WHERE p.id = $2
`

type RestorePostParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestorePost(ctx context.Context, arg RestorePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, restorePost, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restorePostKeepingSlug = `-- name: RestorePostKeepingSlug :execrows
UPDATE core.posts AS p
SET status = 'draft', updated_at = $1
WHERE p.id = $2
`

type RestorePostKeepingSlugParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestorePostKeepingSlug(ctx context.Context, arg RestorePostKeepingSlugParams) (int64, error) {
	result, err := q.db.Exec(ctx, restorePostKeepingSlug, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trashPost = `-- name: TrashPost :execrows
UPDATE core.posts AS p
SET status = 'trash', slug = p.slug || $1::text, updated_at = $2
WHERE p.id = $3
`

type TrashPostParams struct {
	Suffix    string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) TrashPost(ctx context.Context, arg TrashPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, trashPost, arg.Suffix, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE core.posts AS p
SET status = $1, slug = $2, title = $3, content = $4,
    excerpt = $5, published_at = $6, updated_at = $7
WHERE p.id = $8
`

type UpdatePostParams struct {
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	PublishedAt *time.Time
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
