// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/gopherium/gophenberg/internal/media"
)

const countMedia = `-- name: CountMedia :one
SELECT count(*)
FROM core.media m
WHERE ($1::text = '' OR m.media_type = $1)
    AND (
        cardinality($2::text[]) = 0
        OR EXISTS (
            SELECT 1 FROM unnest($2::text[]) AS prefix
            WHERE m.mime_type LIKE prefix || '%'
        )
    )
    AND (
        $3::text = ''
        OR m.title ILIKE '%' || $3 || '%'
        OR m.file ILIKE '%' || $3 || '%'
    )
`

type CountMediaParams struct {
	MediaType string
	Mimes     []string
	Search    string
}

func (q *Queries) CountMedia(ctx context.Context, arg CountMediaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia, arg.MediaType, arg.Mimes, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
SELECT count(*)
FROM core.posts p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
`

type CountPostsParams struct {
	Type   string
	Status string
	Search string
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, arg.Type, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByStatus = `-- name: CountPostsByStatus :many
SELECT p.status, count(*) AS total
FROM core.posts p
WHERE p.type = $1
GROUP BY p.status
`

type CountPostsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountPostsByStatus(ctx context.Context, type_ string) ([]CountPostsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countPostsByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPostsByStatusRow
	for rows.Next() {
		var i CountPostsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO core.media (
    media_type, file, title, alt_text, caption, description,
    mime_type, width, height, filesize, sizes, author_id, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, media_type, file, title, alt_text, caption, description,
    mime_type, width, height, filesize, sizes, author_id, created_at, updated_at
`

type CreateMediaParams struct {
	MediaType   string
	File        string
	Title       string
	AltText     string
	Caption     string
	Description string
	MimeType    string
	Width       int32
	Height      int32
	Filesize    int64
	Sizes       media.RenditionMap
	AuthorID    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.MediaType,
		arg.File,
		arg.Title,
		arg.AltText,
		arg.Caption,
		arg.Description,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.Filesize,
		arg.Sizes,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one

INSERT INTO core.posts (
    id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
RETURNING id, type, status, slug, title, content, excerpt,
    author_id, published_at, created_at, updated_at
`

type CreatePostParams struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Content     string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.AuthorID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO core.post_revisions (
    id, post_id, kind, author_id, title, content, excerpt, created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateRevisionParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	CreatedAt time.Time
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.Exec(ctx, createRevision,
		arg.ID,
		arg.PostID,
		arg.Kind,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.CreatedAt,
	)
	return err
}

const deleteAutosave = `-- name: DeleteAutosave :exec
DELETE FROM core.post_revisions AS r
WHERE r.post_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type DeleteAutosaveParams struct {
	PostID   uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) DeleteAutosave(ctx context.Context, arg DeleteAutosaveParams) error {
	_, err := q.db.Exec(ctx, deleteAutosave, arg.PostID, arg.AuthorID)
	return err
}

const deleteMedia = `-- name: DeleteMedia :one
DELETE FROM core.media AS m
WHERE m.id = $1
RETURNING m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, deleteMedia, id)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM core.posts AS p WHERE p.id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevision = `-- name: DeleteRevision :execrows
DELETE FROM core.post_revisions AS r
WHERE r.post_id = $1 AND r.id = $2
`

type DeleteRevisionParams struct {
	PostID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteRevision(ctx context.Context, arg DeleteRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevision, arg.PostID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAutosave = `-- name: GetAutosave :one
SELECT r.id, r.post_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.created_at
FROM core.post_revisions r
WHERE r.post_id = $1 AND r.author_id = $2 AND r.kind = 'autosave'
`

type GetAutosaveParams struct {
	PostID   uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) GetAutosave(ctx context.Context, arg GetAutosaveParams) (CorePostRevision, error) {
	row := q.db.QueryRow(ctx, getAutosave, arg.PostID, arg.AuthorID)
	var i CorePostRevision
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
FROM core.media m
WHERE m.id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
FROM core.posts p
WHERE p.id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (CorePost, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPost = `-- name: GetPublishedPost :one
SELECT p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
FROM core.posts p
WHERE p.type = $1 AND p.slug = $2 AND p.status = 'published'
`

type GetPublishedPostParams struct {
	Type string
	Slug string
}

func (q *Queries) GetPublishedPost(ctx context.Context, arg GetPublishedPostParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, getPublishedPost, arg.Type, arg.Slug)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT r.id, r.post_id, r.kind, r.author_id, r.title, r.content, r.excerpt, r.created_at
FROM core.post_revisions r
WHERE r.post_id = $1 AND r.id = $2
`

type GetRevisionParams struct {
	PostID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (CorePostRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.PostID, arg.ID)
	var i CorePostRevision
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT s.value FROM core.settings s WHERE s.key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listMedia = `-- name: ListMedia :many
SELECT m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
FROM core.media m
WHERE ($1::text = '' OR m.media_type = $1)
    AND (
        cardinality($2::text[]) = 0
        OR EXISTS (
            SELECT 1 FROM unnest($2::text[]) AS prefix
            WHERE m.mime_type LIKE prefix || '%'
        )
    )
    AND (
        $3::text = ''
        OR m.title ILIKE '%' || $3 || '%'
        OR m.file ILIKE '%' || $3 || '%'
    )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5 OFFSET $4
`

type ListMediaParams struct {
	MediaType string
	Mimes     []string
	Search    string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]CoreMedia, error) {
	rows, err := q.db.Query(ctx, listMedia,
		arg.MediaType,
		arg.Mimes,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreMedia
	for rows.Next() {
		var i CoreMedia
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.File,
			&i.Title,
			&i.AltText,
			&i.Caption,
			&i.Description,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.Filesize,
			&i.Sizes,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.type, p.status, p.slug, p.title, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
FROM core.posts p
WHERE p.type = $1
    AND ($2::text = '' OR p.status = $2)
    AND (
        $3::text = ''
        OR p.title ILIKE '%' || $3 || '%'
        OR p.content ILIKE '%' || $3 || '%'
    )
ORDER BY
    CASE WHEN $4::text = 'title' AND $5::text = 'asc' THEN p.title END ASC,
    CASE WHEN $4::text = 'title' AND $5::text = 'desc' THEN p.title END DESC,
    CASE WHEN $4::text <> 'title' AND $5::text = 'asc'
        THEN COALESCE(p.published_at, p.created_at) END ASC,
    CASE WHEN $4::text <> 'title' AND $5::text <> 'asc'
        THEN COALESCE(p.published_at, p.created_at) END DESC,
    p.id DESC
LIMIT $7 OFFSET $6
`

type ListPostsParams struct {
	Type      string
	Status    string
	Search    string
	OrderBy   string
	OrderDir  string
	RowOffset int32
	RowLimit  int32
}

type ListPostsRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Slug        string
	Title       string
	Excerpt     string
	AuthorID    uuid.UUID
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Type,
		arg.Status,
		arg.Search,
		arg.OrderBy,
		arg.OrderDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.post_id, r.kind, r.author_id, r.title, r.excerpt, r.created_at
FROM core.post_revisions r
WHERE r.post_id = $1
ORDER BY r.created_at DESC, r.id DESC
`

type ListRevisionsRow struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	Kind      string
	AuthorID  uuid.UUID
	Title     string
	Excerpt   string
	CreatedAt time.Time
}

func (q *Queries) ListRevisions(ctx context.Context, postID uuid.UUID) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Kind,
			&i.AuthorID,
			&i.Title,
			&i.Excerpt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRevisions = `-- name: PruneRevisions :exec
DELETE FROM core.post_revisions AS r
WHERE r.id IN (
    SELECT p.id
    FROM core.post_revisions p
    WHERE p.post_id = $1 AND p.kind = 'revision'
    ORDER BY p.created_at DESC, p.id DESC
    OFFSET $2::int
)
`

type PruneRevisionsParams struct {
	PostID uuid.UUID
	Keep   int32
}

func (q *Queries) PruneRevisions(ctx context.Context, arg PruneRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneRevisions, arg.PostID, arg.Keep)
	return err
}

const restorePost = `-- name: RestorePost :one
UPDATE core.posts AS p
SET status = 'draft',
    slug = regexp_replace(p.slug, '-trashed-[a-z0-9]{8}$', ''),
    updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
`

type RestorePostParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestorePost(ctx context.Context, arg RestorePostParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, restorePost, arg.UpdatedAt, arg.ID)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restorePostKeepingSlug = `-- name: RestorePostKeepingSlug :one
UPDATE core.posts AS p
SET status = 'draft', updated_at = $1
WHERE p.id = $2
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
`

type RestorePostKeepingSlugParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RestorePostKeepingSlug(ctx context.Context, arg RestorePostKeepingSlugParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, restorePostKeepingSlug, arg.UpdatedAt, arg.ID)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO core.settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.Exec(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const trashPost = `-- name: TrashPost :one
UPDATE core.posts AS p
SET status = 'trash', slug = p.slug || $1::text, updated_at = $2
WHERE p.id = $3
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
`

type TrashPostParams struct {
	Suffix    string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) TrashPost(ctx context.Context, arg TrashPostParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, trashPost, arg.Suffix, arg.UpdatedAt, arg.ID)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE core.media AS m
SET title = $1, alt_text = $2, caption = $3,
    description = $4, updated_at = $5
WHERE m.id = $6 AND m.updated_at = $7
RETURNING m.id, m.media_type, m.file, m.title, m.alt_text, m.caption, m.description,
    m.mime_type, m.width, m.height, m.filesize, m.sizes, m.author_id, m.created_at, m.updated_at
`

type UpdateMediaParams struct {
	Title             string
	AltText           string
	Caption           string
	Description       string
	UpdatedAt         time.Time
	ID                int64
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (CoreMedia, error) {
	row := q.db.QueryRow(ctx, updateMedia,
		arg.Title,
		arg.AltText,
		arg.Caption,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CoreMedia
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.File,
		&i.Title,
		&i.AltText,
		&i.Caption,
		&i.Description,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Filesize,
		&i.Sizes,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE core.posts AS p
SET status = $1, slug = $2, title = $3, content = $4,
    excerpt = $5, published_at = $6, updated_at = $7
WHERE p.id = $8 AND p.updated_at = $9
RETURNING p.id, p.type, p.status, p.slug, p.title, p.content, p.excerpt,
    p.author_id, p.published_at, p.created_at, p.updated_at
`

type UpdatePostParams struct {
	Status            string
	Slug              string
	Title             string
	Content           string
	Excerpt           string
	PublishedAt       *time.Time
	UpdatedAt         time.Time
	ID                uuid.UUID
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (CorePost, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Status,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CorePost
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAutosave = `-- name: UpsertAutosave :one
INSERT INTO core.post_revisions (
    id, post_id, kind, author_id, title, content, excerpt, created_at
)
VALUES (
    $1, $2, 'autosave', $3, $4, $5, $6, $7
)
ON CONFLICT (post_id, author_id) WHERE kind = 'autosave'
DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    excerpt = EXCLUDED.excerpt,
    created_at = EXCLUDED.created_at
RETURNING id, post_id, kind, author_id, title, content, excerpt, created_at
`

type UpsertAutosaveParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	AuthorID  uuid.UUID
	Title     string
	Content   string
	Excerpt   string
	CreatedAt time.Time
}

func (q *Queries) UpsertAutosave(ctx context.Context, arg UpsertAutosaveParams) (CorePostRevision, error) {
	row := q.db.QueryRow(ctx, upsertAutosave,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.CreatedAt,
	)
	var i CorePostRevision
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Kind,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
	)
	return i, err
}
