// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one

SELECT s.value FROM core.settings s WHERE s.key = $1
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO core.settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.Exec(ctx, setSetting, arg.Key, arg.Value)
	return err
}
