// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: types.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptContentType = `-- name: AdoptContentType :execrows
UPDATE core.content_types SET origin = NULL, updated_at = $1 WHERE key = $2
`

type AdoptContentTypeParams struct {
	UpdatedAt time.Time
	Key       string
}

func (q *Queries) AdoptContentType(ctx context.Context, arg AdoptContentTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, adoptContentType, arg.UpdatedAt, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adoptFieldGroup = `-- name: AdoptFieldGroup :execrows
UPDATE core.field_groups SET origin = NULL, updated_at = $1 WHERE key = $2
`

type AdoptFieldGroupParams struct {
	UpdatedAt time.Time
	Key       string
}

func (q *Queries) AdoptFieldGroup(ctx context.Context, arg AdoptFieldGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, adoptFieldGroup, arg.UpdatedAt, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adoptFieldsInGroup = `-- name: AdoptFieldsInGroup :exec
UPDATE core.content_fields SET origin = NULL, updated_at = $1
WHERE group_id IN (SELECT g.id FROM core.field_groups AS g WHERE g.key = $2)
`

type AdoptFieldsInGroupParams struct {
	UpdatedAt time.Time
	Key       string
}

func (q *Queries) AdoptFieldsInGroup(ctx context.Context, arg AdoptFieldsInGroupParams) error {
	_, err := q.db.Exec(ctx, adoptFieldsInGroup, arg.UpdatedAt, arg.Key)
	return err
}

const carryStrayFieldsOfGroup = `-- name: CarryStrayFieldsOfGroup :exec
WITH RECURSIVE rooted AS (
    SELECT top.id, top.group_id FROM core.content_fields AS top WHERE top.parent_field_id IS NULL
    UNION ALL
    SELECT below.id, rooted.group_id
    FROM core.content_fields AS below JOIN rooted ON below.parent_field_id = rooted.id
)
UPDATE core.content_fields AS carried
SET group_id = rooted.group_id
FROM rooted
WHERE carried.id = rooted.id AND carried.group_id = $1 AND rooted.group_id <> $1
`

func (q *Queries) CarryStrayFieldsOfGroup(ctx context.Context, groupID int32) error {
	_, err := q.db.Exec(ctx, carryStrayFieldsOfGroup, groupID)
	return err
}

const clearContentFieldValues = `-- name: ClearContentFieldValues :exec
UPDATE core.content SET fields = fields - $1::text
WHERE type = ANY($2::text []) AND fields ? $1::text
`

type ClearContentFieldValuesParams struct {
	Key   string
	Types []string
}

func (q *Queries) ClearContentFieldValues(ctx context.Context, arg ClearContentFieldValuesParams) error {
	_, err := q.db.Exec(ctx, clearContentFieldValues, arg.Key, arg.Types)
	return err
}

const clearRevisionFieldValues = `-- name: ClearRevisionFieldValues :exec
UPDATE core.content_revisions r
SET fields = r.fields - $1::text
FROM core.content c
WHERE r.content_id = c.id AND c.type = ANY($2::text []) AND r.fields ? $1::text
`

type ClearRevisionFieldValuesParams struct {
	Key   string
	Types []string
}

func (q *Queries) ClearRevisionFieldValues(ctx context.Context, arg ClearRevisionFieldValuesParams) error {
	_, err := q.db.Exec(ctx, clearRevisionFieldValues, arg.Key, arg.Types)
	return err
}

const countNestedContent = `-- name: CountNestedContent :one

SELECT count(*) FROM core.content p WHERE p.type = $1 AND p.parent_id IS NOT NULL
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CountNestedContent(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countNestedContent, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContentField = `-- name: CreateContentField :one
INSERT INTO core.content_fields (
    group_id, key, label, kind, relates_to, many, required, position, created_at, updated_at, settings, origin
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM core.content_fields WHERE group_id = $1),
    $8, $9, $10, $11
)
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
`

type CreateContentFieldParams struct {
	GroupID   int32
	Key       string
	Label     string
	Kind      string
	RelatesTo *string
	Many      bool
	Required  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Settings  []byte
	Origin    *string
}

func (q *Queries) CreateContentField(ctx context.Context, arg CreateContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, createContentField,
		arg.GroupID,
		arg.Key,
		arg.Label,
		arg.Kind,
		arg.RelatesTo,
		arg.Many,
		arg.Required,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Settings,
		arg.Origin,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}

const createContentType = `-- name: CreateContentType :one
INSERT INTO core.content_types (
    key, singular_label, plural_label, route_word, hierarchical, revisions,
    revision_cap, page_kind, is_default, active, origin, description, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING key, singular_label, plural_label, route_word, hierarchical, revisions,
    revision_cap, page_kind, is_default, active, created_at, updated_at, origin, description
`

type CreateContentTypeParams struct {
	Key           string
	SingularLabel string
	PluralLabel   string
	RouteWord     string
	Hierarchical  bool
	Revisions     bool
	RevisionCap   int32
	PageKind      string
	IsDefault     bool
	Active        bool
	Origin        *string
	Description   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateContentType(ctx context.Context, arg CreateContentTypeParams) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, createContentType,
		arg.Key,
		arg.SingularLabel,
		arg.PluralLabel,
		arg.RouteWord,
		arg.Hierarchical,
		arg.Revisions,
		arg.RevisionCap,
		arg.PageKind,
		arg.IsDefault,
		arg.Active,
		arg.Origin,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Description,
	)
	return i, err
}

const createFieldGroup = `-- name: CreateFieldGroup :one
INSERT INTO core.field_groups (key, title, location, position, origin, created_at, updated_at)
VALUES (
    $1, $2, $3,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM core.field_groups),
    $4, $5, $6
)
RETURNING id, title, location, position, active, created_at, updated_at, origin, key
`

type CreateFieldGroupParams struct {
	Key       string
	Title     string
	Location  []byte
	Origin    *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFieldGroup(ctx context.Context, arg CreateFieldGroupParams) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, createFieldGroup,
		arg.Key,
		arg.Title,
		arg.Location,
		arg.Origin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Key,
	)
	return i, err
}

const createSubContentField = `-- name: CreateSubContentField :one
INSERT INTO core.content_fields (
    group_id, parent_field_id, key, label, kind, relates_to, many, required,
    position, created_at, updated_at, settings, depth, origin
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    (
        SELECT COALESCE(MAX(position), 0) + 1 FROM core.content_fields
        WHERE parent_field_id = $2
    ),
    $9, $10, $11, $12, $13
)
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
`

type CreateSubContentFieldParams struct {
	GroupID       int32
	ParentFieldID pgtype.Int4
	Key           string
	Label         string
	Kind          string
	RelatesTo     *string
	Many          bool
	Required      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Settings      []byte
	Depth         int32
	Origin        *string
}

func (q *Queries) CreateSubContentField(ctx context.Context, arg CreateSubContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, createSubContentField,
		arg.GroupID,
		arg.ParentFieldID,
		arg.Key,
		arg.Label,
		arg.Kind,
		arg.RelatesTo,
		arg.Many,
		arg.Required,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Settings,
		arg.Depth,
		arg.Origin,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}

const deleteContentField = `-- name: DeleteContentField :execrows
DELETE FROM core.content_fields
WHERE group_id = $1 AND key = $2 AND parent_field_id IS NULL
`

type DeleteContentFieldParams struct {
	GroupID int32
	Key     string
}

func (q *Queries) DeleteContentField(ctx context.Context, arg DeleteContentFieldParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContentField, arg.GroupID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContentType = `-- name: DeleteContentType :execrows
DELETE FROM core.content_types AS t WHERE t.key = $1
`

func (q *Queries) DeleteContentType(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContentType, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFieldByID = `-- name: DeleteFieldByID :execrows
DELETE FROM core.content_fields WHERE id = $1
`

func (q *Queries) DeleteFieldByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFieldByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFieldGroup = `-- name: DeleteFieldGroup :execrows
DELETE FROM core.field_groups WHERE id = $1
`

func (q *Queries) DeleteFieldGroup(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFieldGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelationsOfFields = `-- name: DeleteRelationsOfFields :exec
DELETE FROM core.content_relations AS r
USING core.content AS c
WHERE r.from_id = c.id AND c.type = ANY($1::text []) AND r.field_id = ANY($2::integer [])
`

type DeleteRelationsOfFieldsParams struct {
	Types  []string
	Fields []int32
}

func (q *Queries) DeleteRelationsOfFields(ctx context.Context, arg DeleteRelationsOfFieldsParams) error {
	_, err := q.db.Exec(ctx, deleteRelationsOfFields, arg.Types, arg.Fields)
	return err
}

const fieldByID = `-- name: FieldByID :one
SELECT id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
FROM core.content_fields WHERE id = $1
`

func (q *Queries) FieldByID(ctx context.Context, id int32) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, fieldByID, id)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}

const fieldGroupKeys = `-- name: FieldGroupKeys :many
SELECT key FROM core.field_groups ORDER BY key
`

func (q *Queries) FieldGroupKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, fieldGroupKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentType = `-- name: GetContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at, t.origin, t.description
FROM core.content_types t
WHERE t.key = $1
`

func (q *Queries) GetContentType(ctx context.Context, key string) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, getContentType, key)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Description,
	)
	return i, err
}

const groupByLocation = `-- name: GroupByLocation :one
SELECT id, title, location, position, active, created_at, updated_at, origin, key
FROM core.field_groups WHERE location = $1
ORDER BY position, id LIMIT 1
`

func (q *Queries) GroupByLocation(ctx context.Context, location []byte) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, groupByLocation, location)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Key,
	)
	return i, err
}

const listContentFields = `-- name: ListContentFields :many
SELECT id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
FROM core.content_fields ORDER BY group_id, position, id
`

func (q *Queries) ListContentFields(ctx context.Context) ([]CoreContentField, error) {
	rows, err := q.db.Query(ctx, listContentFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentField
	for rows.Next() {
		var i CoreContentField
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Kind,
			&i.RelatesTo,
			&i.Many,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.GroupID,
			&i.Settings,
			&i.ParentFieldID,
			&i.Depth,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentFieldsOfGroup = `-- name: ListContentFieldsOfGroup :many
SELECT id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
FROM core.content_fields WHERE group_id = $1 ORDER BY position, id
`

func (q *Queries) ListContentFieldsOfGroup(ctx context.Context, groupID int32) ([]CoreContentField, error) {
	rows, err := q.db.Query(ctx, listContentFieldsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentField
	for rows.Next() {
		var i CoreContentField
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Kind,
			&i.RelatesTo,
			&i.Many,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.GroupID,
			&i.Settings,
			&i.ParentFieldID,
			&i.Depth,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentTypes = `-- name: ListContentTypes :many
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at, t.origin, t.description
FROM core.content_types t
ORDER BY t.created_at, t.key
`

func (q *Queries) ListContentTypes(ctx context.Context) ([]CoreContentType, error) {
	rows, err := q.db.Query(ctx, listContentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreContentType
	for rows.Next() {
		var i CoreContentType
		if err := rows.Scan(
			&i.Key,
			&i.SingularLabel,
			&i.PluralLabel,
			&i.RouteWord,
			&i.Hierarchical,
			&i.Revisions,
			&i.RevisionCap,
			&i.PageKind,
			&i.IsDefault,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldGroups = `-- name: ListFieldGroups :many
SELECT id, title, location, position, active, created_at, updated_at, origin, key
FROM core.field_groups ORDER BY position, id
`

func (q *Queries) ListFieldGroups(ctx context.Context) ([]CoreFieldGroup, error) {
	rows, err := q.db.Query(ctx, listFieldGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreFieldGroup
	for rows.Next() {
		var i CoreFieldGroup
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContentType = `-- name: LockContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at, t.origin, t.description
FROM core.content_types t
WHERE t.key = $1
FOR UPDATE
`

func (q *Queries) LockContentType(ctx context.Context, key string) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, lockContentType, key)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Description,
	)
	return i, err
}

const lockDefaultContentType = `-- name: LockDefaultContentType :one
SELECT t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at, t.origin, t.description
FROM core.content_types t
WHERE t.is_default
FOR UPDATE
`

func (q *Queries) LockDefaultContentType(ctx context.Context) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, lockDefaultContentType)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Description,
	)
	return i, err
}

const lockFieldGroups = `-- name: LockFieldGroups :exec
SELECT pg_advisory_xact_lock(hashtext('core.field_groups'))
`

func (q *Queries) LockFieldGroups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockFieldGroups)
	return err
}

const recountContentFieldDepth = `-- name: RecountContentFieldDepth :exec
WITH RECURSIVE rooted AS (
    SELECT top.id, $2::integer AS depth FROM core.content_fields AS top WHERE top.id = $3
    UNION ALL
    SELECT below.id, rooted.depth + 1
    FROM core.content_fields AS below JOIN rooted ON below.parent_field_id = rooted.id
) CYCLE id SET looped USING trail
UPDATE core.content_fields AS held
SET depth = rooted.depth, group_id = $1
FROM rooted
WHERE held.id = rooted.id AND NOT rooted.looped
`

type RecountContentFieldDepthParams struct {
	ToGroup int32
	Depth   int32
	ID      int32
}

func (q *Queries) RecountContentFieldDepth(ctx context.Context, arg RecountContentFieldDepthParams) error {
	_, err := q.db.Exec(ctx, recountContentFieldDepth, arg.ToGroup, arg.Depth, arg.ID)
	return err
}

const reorderContentFields = `-- name: ReorderContentFields :execrows
UPDATE core.content_fields
SET position = ordered.position
FROM (
    SELECT key, ordinality AS position
    FROM unnest($2::text []) WITH ORDINALITY AS asked (key, ordinality)
) AS ordered
WHERE core.content_fields.group_id = $1 AND core.content_fields.key = ordered.key
    AND core.content_fields.parent_field_id IS NULL
`

type ReorderContentFieldsParams struct {
	GroupID int32
	Keys    []string
}

func (q *Queries) ReorderContentFields(ctx context.Context, arg ReorderContentFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderContentFields, arg.GroupID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderFieldGroups = `-- name: ReorderFieldGroups :exec
UPDATE core.field_groups
SET position = ordered.position
FROM (
    SELECT id, ordinality AS position
    FROM unnest($1::integer []) WITH ORDINALITY AS asked (id, ordinality)
) AS ordered
WHERE core.field_groups.id = ordered.id
`

func (q *Queries) ReorderFieldGroups(ctx context.Context, ids []int32) error {
	_, err := q.db.Exec(ctx, reorderFieldGroups, ids)
	return err
}

const reorderSubContentFields = `-- name: ReorderSubContentFields :execrows
UPDATE core.content_fields
SET position = ordered.position
FROM (
    SELECT key, ordinality AS position
    FROM unnest($2::text []) WITH ORDINALITY AS asked (key, ordinality)
) AS ordered
WHERE core.content_fields.parent_field_id = $1 AND core.content_fields.key = ordered.key
`

type ReorderSubContentFieldsParams struct {
	ParentFieldID pgtype.Int4
	Keys          []string
}

func (q *Queries) ReorderSubContentFields(ctx context.Context, arg ReorderSubContentFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderSubContentFields, arg.ParentFieldID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reparentContentField = `-- name: ReparentContentField :one
UPDATE core.content_fields AS moved
SET group_id = $1,
    parent_field_id = $2::integer,
    position = (
        SELECT COALESCE(MAX(landing.position), 0) + 1
        FROM core.content_fields AS landing
        WHERE landing.group_id = $1
            AND landing.parent_field_id IS NOT DISTINCT FROM $2::integer
    ),
    updated_at = $3
WHERE moved.id = $4
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
`

type ReparentContentFieldParams struct {
	ToGroup   int32
	ToParent  pgtype.Int4
	UpdatedAt time.Time
	ID        int32
}

func (q *Queries) ReparentContentField(ctx context.Context, arg ReparentContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, reparentContentField,
		arg.ToGroup,
		arg.ToParent,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}

const retypeContentPaths = `-- name: RetypeContentPaths :exec
UPDATE core.content c
SET path = trim(leading '/' from $1::text || '/' ||
        CASE WHEN $2::text = '' THEN c.path
            ELSE substring(c.path from length($2::text) + 2) END),
    updated_at = $3
WHERE c.type = $4
`

type RetypeContentPathsParams struct {
	RouteWord string
	Was       string
	UpdatedAt time.Time
	Key       string
}

func (q *Queries) RetypeContentPaths(ctx context.Context, arg RetypeContentPathsParams) error {
	_, err := q.db.Exec(ctx, retypeContentPaths,
		arg.RouteWord,
		arg.Was,
		arg.UpdatedAt,
		arg.Key,
	)
	return err
}

const stripContentFieldPath = `-- name: StripContentFieldPath :exec
UPDATE core.content
SET fields = core.strip_field_path(fields, $1::text [])
WHERE type = ANY($2::text []) AND fields ? $3::text
`

type StripContentFieldPathParams struct {
	Path  []string
	Types []string
	Key   string
}

func (q *Queries) StripContentFieldPath(ctx context.Context, arg StripContentFieldPathParams) error {
	_, err := q.db.Exec(ctx, stripContentFieldPath, arg.Path, arg.Types, arg.Key)
	return err
}

const stripContentLayout = `-- name: StripContentLayout :exec
UPDATE core.content
SET fields = core.strip_layout(fields, $1::text [])
WHERE type = ANY($2::text []) AND fields ? $3::text
`

type StripContentLayoutParams struct {
	Path  []string
	Types []string
	Key   string
}

func (q *Queries) StripContentLayout(ctx context.Context, arg StripContentLayoutParams) error {
	_, err := q.db.Exec(ctx, stripContentLayout, arg.Path, arg.Types, arg.Key)
	return err
}

const stripRevisionFieldPath = `-- name: StripRevisionFieldPath :exec
UPDATE core.content_revisions r
SET fields = core.strip_field_path(r.fields, $1::text [])
FROM core.content c
WHERE r.content_id = c.id AND c.type = ANY($2::text []) AND r.fields ? $3::text
`

type StripRevisionFieldPathParams struct {
	Path  []string
	Types []string
	Key   string
}

func (q *Queries) StripRevisionFieldPath(ctx context.Context, arg StripRevisionFieldPathParams) error {
	_, err := q.db.Exec(ctx, stripRevisionFieldPath, arg.Path, arg.Types, arg.Key)
	return err
}

const stripRevisionLayout = `-- name: StripRevisionLayout :exec
UPDATE core.content_revisions r
SET fields = core.strip_layout(r.fields, $1::text [])
FROM core.content c
WHERE r.content_id = c.id AND c.type = ANY($2::text []) AND r.fields ? $3::text
`

type StripRevisionLayoutParams struct {
	Path  []string
	Types []string
	Key   string
}

func (q *Queries) StripRevisionLayout(ctx context.Context, arg StripRevisionLayoutParams) error {
	_, err := q.db.Exec(ctx, stripRevisionLayout, arg.Path, arg.Types, arg.Key)
	return err
}

const typeKeys = `-- name: TypeKeys :many
SELECT key FROM core.content_types ORDER BY created_at, key
`

func (q *Queries) TypeKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, typeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentField = `-- name: UpdateContentField :one
UPDATE core.content_fields
SET label = $1, required = $2, settings = $3, updated_at = $4
WHERE group_id = $5 AND key = $6 AND parent_field_id IS NULL
    AND updated_at = $7
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
`

type UpdateContentFieldParams struct {
	Label             string
	Required          bool
	Settings          []byte
	UpdatedAt         time.Time
	GroupID           int32
	Key               string
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateContentField(ctx context.Context, arg UpdateContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, updateContentField,
		arg.Label,
		arg.Required,
		arg.Settings,
		arg.UpdatedAt,
		arg.GroupID,
		arg.Key,
		arg.ExpectedUpdatedAt,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}

const updateContentType = `-- name: UpdateContentType :one
UPDATE core.content_types AS t
SET singular_label = $1, plural_label = $2, route_word = $3,
    hierarchical = $4, revisions = $5, revision_cap = $6,
    page_kind = $7, is_default = $8, active = $9, description = $10,
    updated_at = $11
WHERE t.key = $12
RETURNING t.key, t.singular_label, t.plural_label, t.route_word, t.hierarchical, t.revisions,
    t.revision_cap, t.page_kind, t.is_default, t.active, t.created_at, t.updated_at, t.origin, t.description
`

type UpdateContentTypeParams struct {
	SingularLabel string
	PluralLabel   string
	RouteWord     string
	Hierarchical  bool
	Revisions     bool
	RevisionCap   int32
	PageKind      string
	IsDefault     bool
	Active        bool
	Description   string
	UpdatedAt     time.Time
	Key           string
}

func (q *Queries) UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) (CoreContentType, error) {
	row := q.db.QueryRow(ctx, updateContentType,
		arg.SingularLabel,
		arg.PluralLabel,
		arg.RouteWord,
		arg.Hierarchical,
		arg.Revisions,
		arg.RevisionCap,
		arg.PageKind,
		arg.IsDefault,
		arg.Active,
		arg.Description,
		arg.UpdatedAt,
		arg.Key,
	)
	var i CoreContentType
	err := row.Scan(
		&i.Key,
		&i.SingularLabel,
		&i.PluralLabel,
		&i.RouteWord,
		&i.Hierarchical,
		&i.Revisions,
		&i.RevisionCap,
		&i.PageKind,
		&i.IsDefault,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Description,
	)
	return i, err
}

const updateFieldGroup = `-- name: UpdateFieldGroup :one
UPDATE core.field_groups
SET title = $1, location = $2, active = $3, updated_at = $4
WHERE id = $5
RETURNING id, title, location, position, active, created_at, updated_at, origin, key
`

type UpdateFieldGroupParams struct {
	Title     string
	Location  []byte
	Active    bool
	UpdatedAt time.Time
	ID        int32
}

func (q *Queries) UpdateFieldGroup(ctx context.Context, arg UpdateFieldGroupParams) (CoreFieldGroup, error) {
	row := q.db.QueryRow(ctx, updateFieldGroup,
		arg.Title,
		arg.Location,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CoreFieldGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.Key,
	)
	return i, err
}

const updateSubContentField = `-- name: UpdateSubContentField :one
UPDATE core.content_fields
SET label = $1, required = $2, settings = $3, updated_at = $4
WHERE id = $5 AND parent_field_id IS NOT NULL AND updated_at = $6
RETURNING id, key, label, kind, relates_to, many, required, created_at, updated_at, position, group_id, settings, parent_field_id, depth, origin
`

type UpdateSubContentFieldParams struct {
	Label             string
	Required          bool
	Settings          []byte
	UpdatedAt         time.Time
	ID                int32
	ExpectedUpdatedAt time.Time
}

func (q *Queries) UpdateSubContentField(ctx context.Context, arg UpdateSubContentFieldParams) (CoreContentField, error) {
	row := q.db.QueryRow(ctx, updateSubContentField,
		arg.Label,
		arg.Required,
		arg.Settings,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i CoreContentField
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Kind,
		&i.RelatesTo,
		&i.Many,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.GroupID,
		&i.Settings,
		&i.ParentFieldID,
		&i.Depth,
		&i.Origin,
	)
	return i, err
}
