// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usersettings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserSetting = `-- name: GetUserSetting :one

SELECT u.value FROM core.user_settings u WHERE u.user_id = $1 AND u.key = $2
`

type GetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserSetting, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setUserSetting = `-- name: SetUserSetting :exec
INSERT INTO core.user_settings (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value
`

type SetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
	Value  string
}

func (q *Queries) SetUserSetting(ctx context.Context, arg SetUserSettingParams) error {
	_, err := q.db.Exec(ctx, setUserSetting, arg.UserID, arg.Key, arg.Value)
	return err
}
