unleash:
  workers: 3
  output-statuses: lct
  exclude-files:
    - '(^|/)db/(db|models|queries\.sql)\.go$'
    - '(^|/)testdb\.go$'
    - '(^|/)cmd/'
mutants:
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: true
