unleash:
  workers: 3
  output-statuses: lct
  exclude-files:
    - '(^|/)db/(db|models|[a-z]+\.sql)\.go$'
    - '(^|/)testdb\.go$'
    - '(^|/)cmd/'
    - '(^|/)internal/app/'
mutants:
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: true
