packages:
  - frontend
  - sdk/astro
  - sdk/frontend
  - plugins/*/frontend
  - test/e2e
  - test/theme

overrides:
  react: ^19.2.8
  react-dom: ^19.2.8

peerDependencyRules:
  allowedVersions:
    react: '19'
    react-dom: '19'
    '@types/react': '19'
    typescript: '6'

minimumReleaseAgeExclude:
  - '@gopherium/godmin@0.7.0'
  - '@gopherium/gottext@0.1.0'
  - '@wordpress/dataviews@17.3.0'
  - '@gopherium/react-auth@0.5.0'
  - '@wordpress/i18n@6.26.0'

allowBuilds:
  esbuild: false
  msw: false

patchedDependencies:
  '@wordpress/element@8.4.0': patches/@wordpress__element@8.4.0.patch
