// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	"github.com/gopherium/gophenberg/sdk"
)

func registerPlugins(_ sdk.Deps) ([]sdk.Plugin, error) {
	return []sdk.Plugin{}, nil
}
