// SPDX-License-Identifier: Apache-2.0

// Code generated by pluginwire. DO NOT EDIT.

package main

import (
	feed "github.com/gopherium/gophenberg/plugins/feed"

	"github.com/gopherium/gophenberg/sdk"
)

func registerPlugins(deps sdk.Deps) ([]sdk.Plugin, error) {
	plugins := make([]sdk.Plugin, 0, 1)
	feedPlugin, err := feed.Register(deps)
	if err != nil {
		return nil, err
	}
	plugins = append(plugins, feedPlugin)
	return plugins, nil
}
